/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Carrier.java
 *
 * Created on Mar 9, 2013, 12:45:54 PM
 */
package pos;

import java.awt.*;

/**
 *
 * @author Home
 */
public class Carrier extends javax.swing.JFrame {

    /** Creates new form Carrier */
    public Carrier() {
        initComponents();
        
        setTitle("Carrier Details");
        setSize(660,770);
        setVisible(true);
        getContentPane().setBackground(new Color(202,225,255)); 
        
        Functions.FillCombo(project_nameCombo, "PRONAME", "Project");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labour_daily_chargesLabel = new javax.swing.JLabel();
        project_nameLabel = new javax.swing.JLabel();
        project_nameCombo = new javax.swing.JComboBox();
        date = new org.jdesktop.swingx.JXDatePicker();
        dateLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fromTextField = new javax.swing.JTextField();
        toTextField = new javax.swing.JTextField();
        vehicle_numberLabel = new javax.swing.JLabel();
        vehicle_chargeLabel = new javax.swing.JLabel();
        labour_nameLabel = new javax.swing.JLabel();
        labour_chargeLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        vehicle_numberTextField2 = new javax.swing.JTextField();
        vehicle_chargeTextField1 = new javax.swing.JTextField();
        labour_nameTextField1 = new javax.swing.JTextField();
        labour_chargeTextField1 = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        vehicle_numberTextField1 = new javax.swing.JTextField();
        vehicle_chargeTextField2 = new javax.swing.JTextField();
        vehicle_chargeTextField3 = new javax.swing.JTextField();
        vehicle_numberTextField3 = new javax.swing.JTextField();
        vehicle_numberTextField4 = new javax.swing.JTextField();
        vehicle_chargeTextField4 = new javax.swing.JTextField();
        vehicle_numberTextField5 = new javax.swing.JTextField();
        vehicle_chargeTextField5 = new javax.swing.JTextField();
        labour_nameTextField2 = new javax.swing.JTextField();
        labour_chargeTextField2 = new javax.swing.JTextField();
        labour_nameTextField3 = new javax.swing.JTextField();
        labour_chargeTextField3 = new javax.swing.JTextField();
        labour_nameTextField4 = new javax.swing.JTextField();
        labour_nameTextField5 = new javax.swing.JTextField();
        labour_chargeTextField4 = new javax.swing.JTextField();
        labour_chargeTextField5 = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        labour_daily_chargesLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labour_daily_chargesLabel.setForeground(new java.awt.Color(0, 102, 102));
        labour_daily_chargesLabel.setText("Carrier Details");

        project_nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        project_nameLabel.setText("Project Name");

        project_nameCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        project_nameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        dateLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        dateLabel.setText("Date");

        fromLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fromLabel.setText("From");

        toLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        toLabel.setText("To");

        vehicle_numberLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        vehicle_numberLabel.setText("Vehicle Number");

        vehicle_chargeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        vehicle_chargeLabel.setText("Vehicle Charge");

        labour_nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labour_nameLabel.setText("Labour Name");

        labour_chargeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labour_chargeLabel.setText("Labour Charge");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        vehicle_numberTextField2.setEnabled(false);

        addButton.setText("Add");

        vehicle_numberTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vehicle_numberTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vehicle_numberTextField1FocusLost(evt);
            }
        });

        vehicle_chargeTextField2.setEnabled(false);

        vehicle_chargeTextField3.setEnabled(false);

        vehicle_numberTextField3.setEnabled(false);

        vehicle_numberTextField4.setEnabled(false);

        vehicle_chargeTextField4.setEnabled(false);

        vehicle_numberTextField5.setEnabled(false);

        vehicle_chargeTextField5.setEnabled(false);

        labour_nameTextField2.setEnabled(false);

        labour_chargeTextField2.setEnabled(false);

        labour_nameTextField3.setEnabled(false);

        labour_chargeTextField3.setEnabled(false);

        labour_nameTextField4.setEnabled(false);

        labour_nameTextField5.setEnabled(false);

        labour_chargeTextField4.setEnabled(false);

        labour_chargeTextField5.setEnabled(false);

        totalLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(255, 0, 0));
        totalLabel.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labour_daily_chargesLabel)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel)
                            .addComponent(project_nameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(project_nameCombo, 0, 142, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vehicle_numberTextField5)
                    .addComponent(vehicle_numberTextField4)
                    .addComponent(vehicle_numberTextField2)
                    .addComponent(fromLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vehicle_numberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicle_numberTextField1)
                    .addComponent(vehicle_numberTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toLabel)
                        .addGap(18, 18, 18)
                        .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vehicle_chargeTextField5)
                            .addComponent(vehicle_chargeTextField4)
                            .addComponent(vehicle_chargeTextField3)
                            .addComponent(vehicle_chargeTextField2)
                            .addComponent(vehicle_chargeTextField1)
                            .addComponent(vehicle_chargeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labour_nameTextField5)
                            .addComponent(labour_nameTextField4)
                            .addComponent(labour_nameTextField3)
                            .addComponent(labour_nameTextField2)
                            .addComponent(labour_nameTextField1)
                            .addComponent(labour_nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labour_chargeTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(labour_chargeTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(labour_chargeTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(labour_chargeTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labour_chargeTextField1)
                                .addComponent(labour_chargeLabel)))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(totalLabel)
                .addGap(305, 305, 305))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labour_daily_chargesLabel)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(project_nameLabel)
                    .addComponent(project_nameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLabel)
                    .addComponent(toLabel)
                    .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicle_numberLabel)
                            .addComponent(vehicle_chargeLabel)
                            .addComponent(labour_nameLabel))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vehicle_chargeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vehicle_numberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labour_nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vehicle_numberTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehicle_chargeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vehicle_numberTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehicle_chargeTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vehicle_numberTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehicle_chargeTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vehicle_numberTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehicle_chargeTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labour_nameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labour_nameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labour_nameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labour_nameTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labour_chargeLabel)
                        .addGap(31, 31, 31)
                        .addComponent(labour_chargeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labour_chargeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labour_chargeTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labour_chargeTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labour_chargeTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void vehicle_numberTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vehicle_numberTextField1FocusGained

    vehicle_numberTextField2.setEnabled(true);
    vehicle_chargeTextField2.setEnabled(true);
    
    // TODO add your handling code here:
}//GEN-LAST:event_vehicle_numberTextField1FocusGained

private void vehicle_numberTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vehicle_numberTextField1FocusLost

    if(vehicle_numberTextField1.getText().equals(""))
    {
        vehicle_numberTextField2.setEnabled(false);
        vehicle_chargeTextField2.setEnabled(false);
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_vehicle_numberTextField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Carrier().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private org.jdesktop.swingx.JXDatePicker date;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labour_chargeLabel;
    private javax.swing.JTextField labour_chargeTextField1;
    private javax.swing.JTextField labour_chargeTextField2;
    private javax.swing.JTextField labour_chargeTextField3;
    private javax.swing.JTextField labour_chargeTextField4;
    private javax.swing.JTextField labour_chargeTextField5;
    private javax.swing.JLabel labour_daily_chargesLabel;
    private javax.swing.JLabel labour_nameLabel;
    private javax.swing.JTextField labour_nameTextField1;
    private javax.swing.JTextField labour_nameTextField2;
    private javax.swing.JTextField labour_nameTextField3;
    private javax.swing.JTextField labour_nameTextField4;
    private javax.swing.JTextField labour_nameTextField5;
    private javax.swing.JComboBox project_nameCombo;
    private javax.swing.JLabel project_nameLabel;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel vehicle_chargeLabel;
    private javax.swing.JTextField vehicle_chargeTextField1;
    private javax.swing.JTextField vehicle_chargeTextField2;
    private javax.swing.JTextField vehicle_chargeTextField3;
    private javax.swing.JTextField vehicle_chargeTextField4;
    private javax.swing.JTextField vehicle_chargeTextField5;
    private javax.swing.JLabel vehicle_numberLabel;
    private javax.swing.JTextField vehicle_numberTextField1;
    private javax.swing.JTextField vehicle_numberTextField2;
    private javax.swing.JTextField vehicle_numberTextField3;
    private javax.swing.JTextField vehicle_numberTextField4;
    private javax.swing.JTextField vehicle_numberTextField5;
    // End of variables declaration//GEN-END:variables
}
