
package pos;

import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Home
 */
public class Deduction extends javax.swing.JFrame {
    
    int temp=0;

    /** Creates new form ExtraExpense */
    public Deduction() {
        initComponents();
        setVisible(true);
        setSize(660,670);
        setTitle("Extra Expense");
        setLocation(284,45);
        getContentPane().setBackground(new Color(129,134,138));
        Functions.FillCombo(projectCombo, "PRONAME", "Project");
        AutoCompleteDecorator.decorate(projectCombo);
    }

     public Deduction(int i) {
        initComponents();
        setVisible(true);
        setSize(660,670);
        setTitle("Extra Expense");
        setLocation(238,0);
        getContentPane().setBackground(new Color(129,134,138));
        Functions.FillCombo(projectCombo, "PRONAME", "Project");
        AutoCompleteDecorator.decorate(projectCombo);
        temp=i;
        if (temp==1)
        {
            titleLabel.setText("Extra Expenses");
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        costLabel = new javax.swing.JLabel();
        costTextField = new javax.swing.JTextField();
        m_detailsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTextArea = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        projectCombo = new javax.swing.JComboBox();
        projectLabel = new javax.swing.JLabel();
        rateTextField = new javax.swing.JTextField();
        rateLabel = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        typeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 102));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Deduction");

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nameLabel.setText("Name (item/work)");

        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        quantityLabel.setText("Quantity (item/labour)");

        quantityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantityTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityTextFieldFocusLost(evt);
            }
        });
        quantityTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityTextFieldKeyReleased(evt);
            }
        });

        costLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        costLabel.setText("Total Cost");

        costTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                costTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                costTextFieldFocusLost(evt);
            }
        });
        costTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                costTextFieldKeyReleased(evt);
            }
        });

        m_detailsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        m_detailsLabel.setText("Details");

        detailsTextArea.setColumns(12);
        detailsTextArea.setRows(5);
        detailsTextArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                detailsTextAreaFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(detailsTextArea);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        projectCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        projectLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        projectLabel.setText("Project");

        rateTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rateTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rateTextFieldFocusLost(evt);
            }
        });
        rateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rateTextFieldKeyReleased(evt);
            }
        });

        rateLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        rateLabel.setText("Total Rate");

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Material", "Work" }));

        typeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        typeLabel.setText("Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeLabel)
                    .addComponent(quantityLabel)
                    .addComponent(costLabel)
                    .addComponent(nameLabel)
                    .addComponent(m_detailsLabel)
                    .addComponent(rateLabel)
                    .addComponent(projectLabel))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(188, 188, 188))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projectLabel)
                        .addGap(18, 18, 18)
                        .addComponent(typeLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(quantityLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLabel)
                    .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateLabel)
                    .addComponent(rateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_detailsLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained

        nameLabel.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost

        if(nameTextField.getText().equals(""))
        {
            nameLabel.setForeground(Color.red);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void costTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costTextFieldFocusGained

        costLabel.setForeground(Color.black);
        
        if(nameTextField.getText().equals(""))
        {
            nameLabel.setForeground(Color.red);
        }
        if(quantityTextField.getText().equals(""))
        {
            quantityLabel.setForeground(Color.red);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_costTextFieldFocusGained

    private void costTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costTextFieldFocusLost

        if(costTextField.getText().equals(""))
        {
            costLabel.setForeground(Color.red);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_costTextFieldFocusLost

    private void costTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costTextFieldKeyReleased

        Functions.NumericValidation(costTextField);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_costTextFieldKeyReleased

    private void detailsTextAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_detailsTextAreaFocusGained

        if(nameTextField.getText().equals(""))
        {
            nameLabel.setForeground(Color.red);
        }
        if(quantityTextField.getText().equals(""))
        {
            quantityLabel.setForeground(Color.red);
        }
        if(costTextField.getText().equals(""))
        {
            costLabel.setForeground(Color.red);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsTextAreaFocusGained

    private void quantityTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityTextFieldFocusGained

        nameLabel.setForeground(Color.black);
        
        
    }//GEN-LAST:event_quantityTextFieldFocusGained

    private void quantityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityTextFieldFocusLost

        if(quantityTextField.getText().equals(""))
        {
            nameLabel.setForeground(Color.red);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextFieldFocusLost

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
 
        int flag = 0,quantity=0,cost=0;
        String type="",name="",details="",category="";
        String pname = (String) projectCombo.getSelectedItem();
        if(projectCombo.getSelectedItem().equals("Select"))
        {
            projectLabel.setForeground(Color.red);
            flag++;
        }
        if(typeCombo.getSelectedItem().equals("Select"))
        {
            typeLabel.setForeground(Color.red);
            flag++;
        }
        
      
       
       if(nameTextField.getText().equals(""))
       {
           nameLabel.setForeground(Color.red);
           flag++;
       }
       
       
       if(costTextField.getText().equals(""))
       {
           costLabel.setForeground(Color.red);
           flag++;
       }
       
       if(rateTextField.getText().equals(""))
       {
           rateLabel.setForeground(Color.red);
           flag++;
       }
             
           type= (String) typeCombo.getSelectedItem();
            name = nameTextField.getText();
            quantity= Integer.parseInt(quantityTextField.getText());
            cost    = Integer.parseInt(costTextField.getText());
            details = detailsTextArea.getText();
        int rate = Integer.parseInt(rateTextField.getText());
        
        if(temp==1)
        {
            category= "Extra Expenses";
                   
        }
        
       else
        {
        category="Deduction";    
        cost= -cost;
        rate= -rate;
        }
        
        if (rate<cost)
        {
        JOptionPane.showMessageDialog(null,"Cost cnt be higher than rate" );
        }
            
            
        if(flag==0)
        {   
            try {
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    Connection con = DriverManager.getConnection("jdbc:odbc:indlands","","");
                    java.sql.Date sqlDate = new java.sql.Date(new java.util.Date().getTime());
                    PreparedStatement prp=con.prepareStatement("insert into Deduction(type,pname,wname,quantity,cost,details,odate,category,rate) values(?,?,?,?,?,?,?,?,?)");    
                                               
                        prp.setString(1,type);
                        prp.setString(2,pname);
                        prp.setString(3,name);
                        prp.setInt(4,quantity);
                        prp.setInt(5,cost);
                        prp.setString(6,details);
                        prp.setDate(7,sqlDate);
                        prp.setString(8,category);
                        prp.setInt(9,rate);
                        prp.executeUpdate(); 
                        Functions.DisposeFunc(this);
                        
                         con.commit();
                         con.close();
                   }
            
             catch(SQLException e2)
        {
            JOptionPane.showMessageDialog(null,"Deduction err is"  +e2);
            
        }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,"Deduction err is" +e);
             }
             nameTextField.setText("");
                         quantityTextField.setText("");
                         detailsTextArea.setText("");
                         costTextField.setText("");
                         rateTextField.setText("");
                         projectCombo.setSelectedItem("Select");
                         typeCombo.setSelectedItem("Select");
       
        
    }//GEN-LAST:event_addButtonActionPerformed
    }
    private void quantityTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTextFieldKeyReleased
        Functions.NumericValidation(quantityTextField);
    }//GEN-LAST:event_quantityTextFieldKeyReleased

    private void rateTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_rateTextFieldFocusGained

    private void rateTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_rateTextFieldFocusLost

    private void rateTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rateTextFieldKeyReleased
    Functions.NumericValidation(costTextField);        // TODO add your handling code here:
    }//GEN-LAST:event_rateTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Deduction().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField costTextField;
    private javax.swing.JTextArea detailsTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel m_detailsLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox projectCombo;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JTextField rateTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
