/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LabourDailyCharges.java
 *
 * Created on Feb 28, 2013, 3:25:44 PM
 */
package pos;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Home
 */
public class LabourDailyCharges extends javax.swing.JFrame {

    double total, wage, wage1, wage2, wage3, extra;
    double mno,fno,mwage,fwage,extra1;

    /** Creates new form LabourDailyCharges */
    public LabourDailyCharges() {
        initComponents();
        setTitle("Labour Daily Charges");
        setSize(700,700);
        setVisible(true);
        getContentPane().setBackground(new Color(202,225,255));
        
        type_of_woodLabel.setVisible(false);
        type_of_woodTextField.setVisible(false);
        quantity_usedLabel.setVisible(false);
        quantity_usedTextField.setVisible(false);
               
        nameCombo1.setVisible(false);
        wageTextField1.setVisible(false);
        nameCombo2.setVisible(false);
        wageTextField2.setVisible(false);
        nameCombo3.setVisible(false);
        wageTextField3.setVisible(false);
        
        Functions.FillCombo(project_nameCombo, "PRONAME", "Project");
        Functions.FillCombo(nameCombo, "LABNAME", "Labour");
        Functions.FillCombo(nameCombo1, "LABNAME", "Labour");
        Functions.FillCombo(nameCombo2, "LABNAME", "Labour");
        Functions.FillCombo(nameCombo3, "LABNAME", "Labour");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labour_daily_chargesLabel = new javax.swing.JLabel();
        project_nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        workLabel = new javax.swing.JLabel();
        project_nameCombo = new javax.swing.JComboBox();
        workCombo = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        single_labour_chargesLabel = new javax.swing.JLabel();
        group_labour_chargesLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        wageLabel = new javax.swing.JLabel();
        nameCombo = new javax.swing.JComboBox();
        wageTextField = new javax.swing.JTextField();
        nameCombo1 = new javax.swing.JComboBox();
        wageTextField1 = new javax.swing.JTextField();
        nameCombo2 = new javax.swing.JComboBox();
        wageTextField2 = new javax.swing.JTextField();
        nameCombo3 = new javax.swing.JComboBox();
        wageTextField3 = new javax.swing.JTextField();
        extra_expenseLabel = new javax.swing.JLabel();
        extra_expenseTextField = new javax.swing.JTextField();
        detailsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTextArea = new javax.swing.JTextArea();
        totalLabel = new javax.swing.JLabel();
        label_total = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        maleLabel = new javax.swing.JLabel();
        mnoLabel = new javax.swing.JLabel();
        mnoTextField = new javax.swing.JTextField();
        mwageLabel = new javax.swing.JLabel();
        mwageTextField = new javax.swing.JTextField();
        femaleLabel = new javax.swing.JLabel();
        fwageTextField = new javax.swing.JTextField();
        fwageLabel = new javax.swing.JLabel();
        fnoTextField = new javax.swing.JTextField();
        fnoLabel = new javax.swing.JLabel();
        detailsLabel1 = new javax.swing.JLabel();
        extra_expenseLabel1 = new javax.swing.JLabel();
        extra_expenseTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsTextArea1 = new javax.swing.JTextArea();
        label_total1 = new javax.swing.JLabel();
        totalLabel1 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        type_of_woodLabel = new javax.swing.JLabel();
        quantity_usedLabel = new javax.swing.JLabel();
        type_of_woodTextField = new javax.swing.JTextField();
        quantity_usedTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        labour_daily_chargesLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labour_daily_chargesLabel.setForeground(new java.awt.Color(0, 102, 102));
        labour_daily_chargesLabel.setText("Labour Daily Charges");

        project_nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        project_nameLabel.setText("Project Name");

        dateLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        dateLabel.setText("Date");

        workLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        workLabel.setText("Work");

        project_nameCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        project_nameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        project_nameCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                project_nameComboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                project_nameComboFocusLost(evt);
            }
        });

        workCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        workCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Plumbing", "Electrical", "Laterate", "Plastering", "Painting", "Centering", "Carpentary", "Flooring" }));
        workCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                workComboItemStateChanged(evt);
            }
        });
        workCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                workComboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                workComboFocusLost(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        single_labour_chargesLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        single_labour_chargesLabel.setForeground(new java.awt.Color(0, 102, 102));
        single_labour_chargesLabel.setText("Single Labour Charges");

        group_labour_chargesLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        group_labour_chargesLabel.setForeground(new java.awt.Color(0, 102, 102));
        group_labour_chargesLabel.setText("Group Labour Charges");

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nameLabel.setText("Name");

        wageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        wageLabel.setText("Wage");

        nameCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        nameCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameComboItemStateChanged(evt);
            }
        });

        wageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wageTextFieldKeyReleased(evt);
            }
        });

        nameCombo1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameCombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        nameCombo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameCombo1ItemStateChanged(evt);
            }
        });

        wageTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wageTextField1KeyReleased(evt);
            }
        });

        nameCombo2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameCombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        nameCombo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameCombo2ItemStateChanged(evt);
            }
        });

        wageTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wageTextField2KeyReleased(evt);
            }
        });

        nameCombo3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameCombo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        nameCombo3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameCombo3ItemStateChanged(evt);
            }
        });

        wageTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wageTextField3KeyReleased(evt);
            }
        });

        extra_expenseLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        extra_expenseLabel.setText("Extra Expense");

        extra_expenseTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                extra_expenseTextFieldKeyReleased(evt);
            }
        });

        detailsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        detailsLabel.setText("Details");

        detailsTextArea.setColumns(15);
        detailsTextArea.setRows(5);
        jScrollPane1.setViewportView(detailsTextArea);

        totalLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalLabel.setText("Total");

        label_total.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        label_total.setForeground(new java.awt.Color(255, 0, 0));
        label_total.setText("Cash");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        maleLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        maleLabel.setForeground(new java.awt.Color(0, 102, 102));
        maleLabel.setText("Male");

        mnoLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mnoLabel.setText("No :");

        mnoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mnoTextFieldKeyReleased(evt);
            }
        });

        mwageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mwageLabel.setText("Wage");

        mwageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mwageTextFieldKeyReleased(evt);
            }
        });

        femaleLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        femaleLabel.setForeground(new java.awt.Color(0, 102, 102));
        femaleLabel.setText("Female");

        fwageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fwageTextFieldKeyReleased(evt);
            }
        });

        fwageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fwageLabel.setText("Wage");

        fnoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnoTextFieldKeyReleased(evt);
            }
        });

        fnoLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fnoLabel.setText("No :");

        detailsLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        detailsLabel1.setText("Details");

        extra_expenseLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        extra_expenseLabel1.setText("Extra Expense");

        extra_expenseTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                extra_expenseTextField1KeyReleased(evt);
            }
        });

        detailsTextArea1.setColumns(15);
        detailsTextArea1.setRows(5);
        jScrollPane2.setViewportView(detailsTextArea1);

        label_total1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        label_total1.setForeground(new java.awt.Color(255, 0, 0));
        label_total1.setText("Cash");

        totalLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalLabel1.setText("Total");

        type_of_woodLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        type_of_woodLabel.setText("Type Of Wood");

        quantity_usedLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        quantity_usedLabel.setText("Quantity Used");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(project_nameLabel)
                    .addComponent(workLabel)
                    .addComponent(dateLabel)
                    .addComponent(type_of_woodLabel)
                    .addComponent(quantity_usedLabel))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantity_usedTextField)
                    .addComponent(type_of_woodTextField)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(workCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(project_nameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalLabel)
                                .addGap(123, 123, 123)
                                .addComponent(label_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(single_labour_chargesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(wageTextField)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nameCombo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(wageTextField1)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nameCombo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(wageTextField2)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(113, 113, 113)
                                .addComponent(wageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(detailsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(extra_expenseLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(extra_expenseTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameCombo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(22, 22, 22)
                                        .addComponent(wageTextField3)))
                                .addGap(7, 7, 7)))
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(group_labour_chargesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(totalLabel1)
                                                .addGap(39, 39, 39)
                                                .addComponent(label_total1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(mnoLabel)
                                                            .addComponent(fnoLabel))
                                                        .addGap(28, 28, 28)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(mnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(mwageLabel))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(fnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(45, 45, 45)
                                                                .addComponent(fwageLabel)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(fwageTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(mwageTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(detailsLabel1)
                                                        .addGap(56, 56, 56)
                                                        .addComponent(jScrollPane2))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(extra_expenseLabel1)
                                                        .addGap(63, 63, 63)
                                                        .addComponent(extra_expenseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(14, 14, 14))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(maleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(femaleLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(labour_daily_chargesLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labour_daily_chargesLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(project_nameLabel)
                    .addComponent(project_nameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(workCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(workLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type_of_woodLabel)
                    .addComponent(type_of_woodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quantity_usedLabel)
                    .addComponent(quantity_usedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(group_labour_chargesLabel)
                            .addComponent(single_labour_chargesLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(wageLabel)
                                    .addComponent(nameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(wageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(wageTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(wageTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wageTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(extra_expenseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(extra_expenseLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detailsLabel)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_total)
                                    .addComponent(totalLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(maleLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(mwageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mwageLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(mnoLabel)
                                            .addComponent(mnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femaleLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(fnoLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(fnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fwageLabel)
                                            .addComponent(fwageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(extra_expenseLabel1)
                                    .addComponent(extra_expenseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detailsLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_total1)
                                    .addComponent(totalLabel1)))))
                    .addComponent(jSeparator2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void project_nameComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_project_nameComboFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_project_nameComboFocusGained

private void project_nameComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_project_nameComboFocusLost
    // TODO add your handling code here:
}//GEN-LAST:event_project_nameComboFocusLost

private void workComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workComboFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_workComboFocusGained

private void workComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workComboFocusLost
    // TODO add your handling code here:
}//GEN-LAST:event_workComboFocusLost

private void nameComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameComboItemStateChanged

    if(nameCombo.getSelectedItem().equals("Select"))
    {
        nameCombo1.setVisible(false);
        wageTextField1.setVisible(false);
        nameCombo2.setVisible(false);
        wageTextField2.setVisible(false);
        nameCombo3.setVisible(false);
        wageTextField3.setVisible(false);
    }
    else
    {
        nameCombo1.setVisible(true);
        wageTextField1.setVisible(true);
    }
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_nameComboItemStateChanged

private void nameCombo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameCombo1ItemStateChanged

    if(nameCombo1.getSelectedItem().equals("Select"))
    {
        nameCombo2.setVisible(false);
        wageTextField2.setVisible(false);
        nameCombo3.setVisible(false);
        wageTextField3.setVisible(false);
    }
    else
    {
        nameCombo2.setVisible(true);
        wageTextField2.setVisible(true);
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_nameCombo1ItemStateChanged

private void nameCombo2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameCombo2ItemStateChanged

    if(nameCombo2.getSelectedItem().equals("Select"))
    {
        nameCombo3.setVisible(false);
        wageTextField3.setVisible(false);
    }
    else
    {
        nameCombo3.setVisible(true);
        wageTextField3.setVisible(true);
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_nameCombo2ItemStateChanged

private void nameCombo3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameCombo3ItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_nameCombo3ItemStateChanged

private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

    if((project_nameCombo.getSelectedItem().equals("Select")
            || workCombo.getSelectedItem().equals("Select"))
            || ((nameCombo.getSelectedItem().equals("Select")
            || wageTextField.getText().equals(""))
            && ((mnoTextField.getText().equals("")
            || mwageTextField.getText().equals(""))
            && (fnoTextField.getText().equals("")
            || fwageTextField.getText().equals("")))))
    {
        JOptionPane.showMessageDialog(null,"Enter All Appropriate Field");
    }
    else
    {
        JOptionPane.showMessageDialog(null,"Done");
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_addButtonActionPerformed

private void wageTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wageTextFieldKeyReleased

    if(Functions.NumericValidate(wageTextField))
    {
        if(wageTextField.getText().equals(""))
        {
            wage=0;
        }
        if(wageTextField1.getText().equals(""))
        {
            wage1=0;
        }
        if(wageTextField2.getText().equals(""))
        {
            wage2=0;
        }
        if(wageTextField3.getText().equals(""))
        {
            wage3=0;
        }
        if(!wageTextField.getText().equals(""))
        {
            wage = Double.parseDouble(wageTextField.getText());
        }
        if(!wageTextField1.getText().equals(""))
        {
            wage1 = Double.parseDouble(wageTextField1.getText());
        }
        if(!wageTextField2.getText().equals(""))
        {
            wage2 = Double.parseDouble(wageTextField2.getText());
        }
        if(!wageTextField3.getText().equals(""))
        {
            wage3 = Double.parseDouble(wageTextField3.getText());
        }
        if(extra_expenseTextField.getText().equals(""))
        {
            extra=0;
        }
        if(!extra_expenseTextField.getText().equals(""))
        {
            extra = Double.parseDouble(extra_expenseTextField.getText());
        }
        total = wage+wage1+wage2+wage3+extra;
        label_total.setText(Double.toString(total));
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_wageTextFieldKeyReleased

private void wageTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wageTextField1KeyReleased
    
    if(Functions.NumericValidate(wageTextField1))
    {
        if(wageTextField.getText().equals(""))
        {
            wage=0;
        }
        if(wageTextField1.getText().equals(""))
        {
            wage1=0;
        }
        if(wageTextField2.getText().equals(""))
        {
            wage2=0;
        }
        if(wageTextField3.getText().equals(""))
        {
            wage3=0;
        }
        if(!wageTextField.getText().equals(""))
        {
            wage = Double.parseDouble(wageTextField.getText());
        }
        if(!wageTextField1.getText().equals(""))
        {
            wage1 = Double.parseDouble(wageTextField1.getText());
        }
        if(!wageTextField2.getText().equals(""))
        {
            wage2 = Double.parseDouble(wageTextField2.getText());
        }
        if(!wageTextField3.getText().equals(""))
        {
            wage3 = Double.parseDouble(wageTextField3.getText());
        }
        if(extra_expenseTextField.getText().equals(""))
        {
            extra=0;
        }
        if(!extra_expenseTextField.getText().equals(""))
        {
            extra = Double.parseDouble(extra_expenseTextField.getText());
        }
        total = wage+wage1+wage2+wage3+extra;
        label_total.setText(Double.toString(total));
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_wageTextField1KeyReleased

private void wageTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wageTextField2KeyReleased

    if(Functions.NumericValidate(wageTextField2))
    {
        if(wageTextField.getText().equals(""))
        {
            wage=0;
        }
        if(wageTextField1.getText().equals(""))
        {
            wage1=0;
        }
        if(wageTextField2.getText().equals(""))
        {
            wage2=0;
        }
        if(wageTextField3.getText().equals(""))
        {
            wage3=0;
        }
        if(!wageTextField.getText().equals(""))
        {
            wage = Double.parseDouble(wageTextField.getText());
        }
        if(!wageTextField1.getText().equals(""))
        {
            wage1 = Double.parseDouble(wageTextField1.getText());
        }
        if(!wageTextField2.getText().equals(""))
        {
            wage2 = Double.parseDouble(wageTextField2.getText());
        }
        if(!wageTextField3.getText().equals(""))
        {
            wage3 = Double.parseDouble(wageTextField3.getText());
        }
        if(extra_expenseTextField.getText().equals(""))
        {
            extra=0;
        }
        if(!extra_expenseTextField.getText().equals(""))
        {
            extra = Double.parseDouble(extra_expenseTextField.getText());
        }
        total = wage+wage1+wage2+wage3+extra;
        label_total.setText(Double.toString(total));
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_wageTextField2KeyReleased

private void wageTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wageTextField3KeyReleased

    if(Functions.NumericValidate(wageTextField3))
    {
        if(wageTextField.getText().equals(""))
        {
            wage=0;
        }
        if(wageTextField1.getText().equals(""))
        {
            wage1=0;
        }
        if(wageTextField2.getText().equals(""))
        {
            wage2=0;
        }
        if(wageTextField3.getText().equals(""))
        {
            wage3=0;
        }
        if(!wageTextField.getText().equals(""))
        {
            wage = Double.parseDouble(wageTextField.getText());
        }
        if(!wageTextField1.getText().equals(""))
        {
            wage1 = Double.parseDouble(wageTextField1.getText());
        }
        if(!wageTextField2.getText().equals(""))
        {
            wage2 = Double.parseDouble(wageTextField2.getText());
        }
        if(!wageTextField3.getText().equals(""))
        {
            wage3 = Double.parseDouble(wageTextField3.getText());
        }
        if(extra_expenseTextField.getText().equals(""))
        {
            extra=0;
        }
        if(!extra_expenseTextField.getText().equals(""))
        {
            extra = Double.parseDouble(extra_expenseTextField.getText());
        }
        total = wage+wage1+wage2+wage3+extra;
        label_total.setText(Double.toString(total));
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_wageTextField3KeyReleased

private void extra_expenseTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extra_expenseTextFieldKeyReleased

    if(Functions.NumericValidate(extra_expenseTextField))
    {
        if(wageTextField.getText().equals(""))
        {
            wage=0;
        }
        if(wageTextField1.getText().equals(""))
        {
            wage1=0;
        }
        if(wageTextField2.getText().equals(""))
        {
            wage2=0;
        }
        if(wageTextField3.getText().equals(""))
        {
            wage3=0;
        }
        if(!wageTextField.getText().equals(""))
        {
            wage = Double.parseDouble(wageTextField.getText());
        }
        if(!wageTextField1.getText().equals(""))
        {
            wage1 = Double.parseDouble(wageTextField1.getText());
        }
        if(!wageTextField2.getText().equals(""))
        {
            wage2 = Double.parseDouble(wageTextField2.getText());
        }
        if(!wageTextField3.getText().equals(""))
        {
            wage3 = Double.parseDouble(wageTextField3.getText());
        }
        if(extra_expenseTextField.getText().equals(""))
        {
            extra=0;
        }
        if(!extra_expenseTextField.getText().equals(""))
        {
            extra = Double.parseDouble(extra_expenseTextField.getText());
        }
        total = wage+wage1+wage2+wage3+extra;
        label_total.setText(Double.toString(total));
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_extra_expenseTextFieldKeyReleased

private void mnoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnoTextFieldKeyReleased

    if(Functions.NumericValidate(mnoTextField))
    {
        if(mnoTextField.getText().equals(""))
        {
            mno=0;
        }
        if(mwageTextField.getText().equals(""))
        {
            mwage=0;
        }
        if(fnoTextField.getText().equals(""))
        {
            fno=0;
        }
        if(fwageTextField.getText().equals(""))
        {
            fwage=0;
        }
        if(extra_expenseTextField1.getText().equals(""))
        {
            extra1=0;
        }
        if(!mnoTextField.getText().equals(""))
        {
            mno = Double.parseDouble(mnoTextField.getText());
        }
        if(!mwageTextField.getText().equals(""))
        {
            mwage = Double.parseDouble(mwageTextField.getText());
        }
        if(!fnoTextField.getText().equals(""))
        {
            fno = Double.parseDouble(fnoTextField.getText());
        }
        if(!fwageTextField.getText().equals(""))
        {
            fwage = Double.parseDouble(fwageTextField.getText());
        }
        if(!extra_expenseTextField1.getText().equals(""))
        {
            extra1 = Double.parseDouble(extra_expenseTextField1.getText());
        }
        total = (mno*mwage)+(fno*fwage)+extra1;
        label_total1.setText(Double.toString(total));
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_mnoTextFieldKeyReleased

private void mwageTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mwageTextFieldKeyReleased

    if(Functions.NumericValidate(mwageTextField))
    {
        if(mnoTextField.getText().equals(""))
        {
            mno=0;
        }
        if(mwageTextField.getText().equals(""))
        {
            mwage=0;
        }
        if(fnoTextField.getText().equals(""))
        {
            fno=0;
        }
        if(fwageTextField.getText().equals(""))
        {
            fwage=0;
        }
        if(extra_expenseTextField1.getText().equals(""))
        {
            extra1=0;
        }
        if(!mnoTextField.getText().equals(""))
        {
            mno = Double.parseDouble(mnoTextField.getText());
        }
        if(!mwageTextField.getText().equals(""))
        {
            mwage = Double.parseDouble(mwageTextField.getText());
        }
        if(!fnoTextField.getText().equals(""))
        {
            fno = Double.parseDouble(fnoTextField.getText());
        }
        if(!fwageTextField.getText().equals(""))
        {
            fwage = Double.parseDouble(fwageTextField.getText());
        }
        if(!extra_expenseTextField1.getText().equals(""))
        {
            extra1 = Double.parseDouble(extra_expenseTextField1.getText());
        }
        total = (mno*mwage)+(fno*fwage)+extra1;
        label_total1.setText(Double.toString(total));
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_mwageTextFieldKeyReleased

private void fnoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnoTextFieldKeyReleased

    if(Functions.NumericValidate(fnoTextField))
    {
        if(mnoTextField.getText().equals(""))
        {
            mno=0;
        }
        if(mwageTextField.getText().equals(""))
        {
            mwage=0;
        }
        if(fnoTextField.getText().equals(""))
        {
            fno=0;
        }
        if(fwageTextField.getText().equals(""))
        {
            fwage=0;
        }
        if(extra_expenseTextField1.getText().equals(""))
        {
            extra1=0;
        }
        if(!mnoTextField.getText().equals(""))
        {
            mno = Double.parseDouble(mnoTextField.getText());
        }
        if(!mwageTextField.getText().equals(""))
        {
            mwage = Double.parseDouble(mwageTextField.getText());
        }
        if(!fnoTextField.getText().equals(""))
        {
            fno = Double.parseDouble(fnoTextField.getText());
        }
        if(!fwageTextField.getText().equals(""))
        {
            fwage = Double.parseDouble(fwageTextField.getText());
        }
        if(!extra_expenseTextField1.getText().equals(""))
        {
            extra1 = Double.parseDouble(extra_expenseTextField1.getText());
        }
        total = (mno*mwage)+(fno*fwage)+extra1;
        label_total1.setText(Double.toString(total));
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_fnoTextFieldKeyReleased

private void fwageTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fwageTextFieldKeyReleased

    if(Functions.NumericValidate(fwageTextField))
    {
        if(mnoTextField.getText().equals(""))
        {
            mno=0;
        }
        if(mwageTextField.getText().equals(""))
        {
            mwage=0;
        }
        if(fnoTextField.getText().equals(""))
        {
            fno=0;
        }
        if(fwageTextField.getText().equals(""))
        {
            fwage=0;
        }
        if(extra_expenseTextField1.getText().equals(""))
        {
            extra1=0;
        }
        if(!mnoTextField.getText().equals(""))
        {
            mno = Double.parseDouble(mnoTextField.getText());
        }
        if(!mwageTextField.getText().equals(""))
        {
            mwage = Double.parseDouble(mwageTextField.getText());
        }
        if(!fnoTextField.getText().equals(""))
        {
            fno = Double.parseDouble(fnoTextField.getText());
        }
        if(!fwageTextField.getText().equals(""))
        {
            fwage = Double.parseDouble(fwageTextField.getText());
        }
        if(!extra_expenseTextField1.getText().equals(""))
        {
            extra1 = Double.parseDouble(extra_expenseTextField1.getText());
        }
        total = (mno*mwage)+(fno*fwage)+extra1;
        label_total1.setText(Double.toString(total));
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_fwageTextFieldKeyReleased

private void extra_expenseTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extra_expenseTextField1KeyReleased

    if(Functions.NumericValidate(extra_expenseTextField1))
    {
        if(mnoTextField.getText().equals(""))
        {
            mno=0;
        }
        if(mwageTextField.getText().equals(""))
        {
            mwage=0;
        }
        if(fnoTextField.getText().equals(""))
        {
            fno=0;
        }
        if(fwageTextField.getText().equals(""))
        {
            fwage=0;
        }
        if(extra_expenseTextField1.getText().equals(""))
        {
            extra1=0;
        }
        if(!mnoTextField.getText().equals(""))
        {
            mno = Double.parseDouble(mnoTextField.getText());
        }
        if(!mwageTextField.getText().equals(""))
        {
            mwage = Double.parseDouble(mwageTextField.getText());
        }
        if(!fnoTextField.getText().equals(""))
        {
            fno = Double.parseDouble(fnoTextField.getText());
        }
        if(!fwageTextField.getText().equals(""))
        {
            fwage = Double.parseDouble(fwageTextField.getText());
        }
        if(!extra_expenseTextField1.getText().equals(""))
        {
            extra1 = Double.parseDouble(extra_expenseTextField1.getText());
        }
        total = (mno*mwage)+(fno*fwage)+extra1;
        label_total1.setText(Double.toString(total));
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_extra_expenseTextField1KeyReleased

    private void workComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_workComboItemStateChanged

        if(workCombo.getSelectedItem().equals("Carpentary"))
        {
            type_of_woodLabel.setVisible(true);
            type_of_woodTextField.setVisible(true);
            quantity_usedLabel.setVisible(true);
            quantity_usedTextField.setVisible(true);
        }
        else
        {
            type_of_woodLabel.setVisible(false);
            type_of_woodTextField.setVisible(false);
            quantity_usedLabel.setVisible(false);
            quantity_usedTextField.setVisible(false);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_workComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LabourDailyCharges().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JLabel detailsLabel1;
    private javax.swing.JTextArea detailsTextArea;
    private javax.swing.JTextArea detailsTextArea1;
    private javax.swing.JLabel extra_expenseLabel;
    private javax.swing.JLabel extra_expenseLabel1;
    private javax.swing.JTextField extra_expenseTextField;
    private javax.swing.JTextField extra_expenseTextField1;
    private javax.swing.JLabel femaleLabel;
    private javax.swing.JLabel fnoLabel;
    private javax.swing.JTextField fnoTextField;
    private javax.swing.JLabel fwageLabel;
    private javax.swing.JTextField fwageTextField;
    private javax.swing.JLabel group_labour_chargesLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel label_total1;
    private javax.swing.JLabel labour_daily_chargesLabel;
    private javax.swing.JLabel maleLabel;
    private javax.swing.JLabel mnoLabel;
    private javax.swing.JTextField mnoTextField;
    private javax.swing.JLabel mwageLabel;
    private javax.swing.JTextField mwageTextField;
    private javax.swing.JComboBox nameCombo;
    private javax.swing.JComboBox nameCombo1;
    private javax.swing.JComboBox nameCombo2;
    private javax.swing.JComboBox nameCombo3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox project_nameCombo;
    private javax.swing.JLabel project_nameLabel;
    private javax.swing.JLabel quantity_usedLabel;
    private javax.swing.JTextField quantity_usedTextField;
    private javax.swing.JLabel single_labour_chargesLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalLabel1;
    private javax.swing.JLabel type_of_woodLabel;
    private javax.swing.JTextField type_of_woodTextField;
    private javax.swing.JLabel wageLabel;
    private javax.swing.JTextField wageTextField;
    private javax.swing.JTextField wageTextField1;
    private javax.swing.JTextField wageTextField2;
    private javax.swing.JTextField wageTextField3;
    private javax.swing.JComboBox workCombo;
    private javax.swing.JLabel workLabel;
    // End of variables declaration//GEN-END:variables
}
