/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LabourDailyCharges.java
 *
 * Created on Feb 28, 2013, 3:25:44 PM
 */
package pos;

import java.awt.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Home
 */
public class LabourDailyCharges extends javax.swing.JFrame {

    int total, wage, wage1, wage2, wage3, wage4;
    
    /** Creates new form LabourDailyCharges */
    public LabourDailyCharges() {
        initComponents();
        setTitle("Labour Daily Charges");
        setSize(660,770);
        setVisible(true);
        getContentPane().setBackground(new Color(202,225,255)); 
        
        nameCombo1.setVisible(false);
        wageTextField1.setVisible(false);
        nameCombo2.setVisible(false);
        wageTextField2.setVisible(false);
        nameCombo3.setVisible(false);
        wageTextField3.setVisible(false);
        nameCombo4.setVisible(false);
        wageTextField4.setVisible(false);
        
        try
        {            
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con = DriverManager.getConnection("jdbc:odbc:indlands","","");
            Statement  st = con.createStatement();
            ResultSet res = st.executeQuery("select PRONAME from Project");
            while(res.next())
            {
               project_nameCombo.addItem(res.getString("PRONAME")); 
            }
            ResultSet res1 = st.executeQuery("select LABNAME from Labour");
            while(res1.next())
            {
                nameCombo.addItem(res1.getString("LABNAME"));
    }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"INVALID datatype");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"The error is1:"+e);
            System.out.println(e.getMessage());
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labour_daily_chargesLabel = new javax.swing.JLabel();
        project_nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        workLabel = new javax.swing.JLabel();
        project_nameCombo = new javax.swing.JComboBox();
        workCombo = new javax.swing.JComboBox();
        dayCombo = new javax.swing.JComboBox();
        monthCombo = new javax.swing.JComboBox();
        yearCombo = new javax.swing.JComboBox();
        label_project_name = new javax.swing.JLabel();
        label_work = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        single_labour_chargesLabel = new javax.swing.JLabel();
        group_labour_chargesLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        wageLabel = new javax.swing.JLabel();
        nameCombo = new javax.swing.JComboBox();
        wageTextField = new javax.swing.JTextField();
        nameCombo1 = new javax.swing.JComboBox();
        wageTextField1 = new javax.swing.JTextField();
        nameCombo2 = new javax.swing.JComboBox();
        wageTextField2 = new javax.swing.JTextField();
        nameCombo3 = new javax.swing.JComboBox();
        wageTextField3 = new javax.swing.JTextField();
        nameCombo4 = new javax.swing.JComboBox();
        wageTextField4 = new javax.swing.JTextField();
        extra_expenseLabel = new javax.swing.JLabel();
        extra_expenseTextField = new javax.swing.JTextField();
        detailsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTextArea = new javax.swing.JTextArea();
        totalLabel = new javax.swing.JLabel();
        label_total = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        maleLabel = new javax.swing.JLabel();
        mnoLabel = new javax.swing.JLabel();
        mnoTextField = new javax.swing.JTextField();
        mwageLabel = new javax.swing.JLabel();
        mwageTextField = new javax.swing.JTextField();
        femaleLabel = new javax.swing.JLabel();
        fwageTextField = new javax.swing.JTextField();
        fwageLabel = new javax.swing.JLabel();
        fnoTextField = new javax.swing.JTextField();
        fnoLabel = new javax.swing.JLabel();
        detailsLabel1 = new javax.swing.JLabel();
        extra_expenseLabel1 = new javax.swing.JLabel();
        extra_expenseTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsTextArea1 = new javax.swing.JTextArea();
        label_total1 = new javax.swing.JLabel();
        totalLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        labour_daily_chargesLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labour_daily_chargesLabel.setForeground(new java.awt.Color(0, 102, 102));
        labour_daily_chargesLabel.setText("Labour Daily Charges");

        project_nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        project_nameLabel.setText("Project Name");

        dateLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        dateLabel.setText("Date");

        workLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        workLabel.setText("Work");

        project_nameCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        project_nameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        project_nameCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                project_nameComboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                project_nameComboFocusLost(evt);
            }
        });

        workCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        workCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Plumbing", "Electrical", "Laterate", "Plastering", "Painting", "Centering", "Carpentary", "Flooring" }));
        workCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                workComboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                workComboFocusLost(evt);
            }
        });

        dayCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        dayCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayComboActionPerformed(evt);
            }
        });

        monthCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        monthCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        monthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboActionPerformed(evt);
            }
        });

        yearCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        yearCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        yearCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboActionPerformed(evt);
            }
        });
        yearCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearComboFocusLost(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        single_labour_chargesLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        single_labour_chargesLabel.setForeground(new java.awt.Color(0, 102, 102));
        single_labour_chargesLabel.setText("Single Labour Charges");

        group_labour_chargesLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        group_labour_chargesLabel.setForeground(new java.awt.Color(0, 102, 102));
        group_labour_chargesLabel.setText("Group Labour Charges");

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nameLabel.setText("Name");

        wageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        wageLabel.setText("Wage");

        nameCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        nameCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameComboItemStateChanged(evt);
            }
        });
        nameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboActionPerformed(evt);
            }
        });

        nameCombo1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameCombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "name" }));
        nameCombo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameCombo1ItemStateChanged(evt);
            }
        });

        nameCombo2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameCombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "name" }));
        nameCombo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameCombo2ItemStateChanged(evt);
            }
        });

        nameCombo3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameCombo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "name" }));
        nameCombo3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameCombo3ItemStateChanged(evt);
            }
        });

        nameCombo4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameCombo4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "name" }));

        extra_expenseLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        extra_expenseLabel.setText("Extra Expense");

        detailsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        detailsLabel.setText("Details");

        detailsTextArea.setColumns(15);
        detailsTextArea.setRows(5);
        jScrollPane1.setViewportView(detailsTextArea);

        totalLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalLabel.setText("Total");

        label_total.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        label_total.setForeground(new java.awt.Color(255, 0, 0));
        label_total.setText("Cash");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        maleLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        maleLabel.setForeground(new java.awt.Color(0, 102, 102));
        maleLabel.setText("Male");

        mnoLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mnoLabel.setText("No :");

        mwageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mwageLabel.setText("Wage");

        femaleLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        femaleLabel.setForeground(new java.awt.Color(0, 102, 102));
        femaleLabel.setText("Female");

        fwageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fwageLabel.setText("Wage");

        fnoLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fnoLabel.setText("No :");

        detailsLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        detailsLabel1.setText("Details");

        extra_expenseLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        extra_expenseLabel1.setText("Extra Expense");

        detailsTextArea1.setColumns(15);
        detailsTextArea1.setRows(5);
        jScrollPane2.setViewportView(detailsTextArea1);

        label_total1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        label_total1.setForeground(new java.awt.Color(255, 0, 0));
        label_total1.setText("Cash");

        totalLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalLabel1.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(labour_daily_chargesLabel)
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(project_nameLabel)
                    .addComponent(workLabel)
                    .addComponent(dateLabel))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(workCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(project_nameCombo, 0, 186, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(label_project_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_date)
                            .addComponent(label_work))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(single_labour_chargesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(wageTextField)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameCombo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(wageTextField1)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameCombo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(wageTextField2)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameCombo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(wageTextField3)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(113, 113, 113)
                                .addComponent(wageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameCombo4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(extra_expenseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(39, 39, 39)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(extra_expenseTextField)
                                    .addComponent(wageTextField4))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(detailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(35, 35, 35))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(50, 50, 50)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(group_labour_chargesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(3, 3, 3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addComponent(maleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(98, 98, 98))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addComponent(femaleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(88, 88, 88))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fnoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fnoTextField)
                                        .addGap(18, 18, 18)
                                        .addComponent(fwageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fwageTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mnoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mnoTextField)
                                        .addGap(18, 18, 18)
                                        .addComponent(mwageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mwageTextField)))
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(extra_expenseLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(36, 36, 36)
                                        .addComponent(extra_expenseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(detailsLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(24, 24, 24))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(totalLabel1)
                                                .addGap(39, 39, 39)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_total1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(14, 14, 14)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extra_expenseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extra_expenseLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detailsLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_total1)
                            .addComponent(totalLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labour_daily_chargesLabel)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(project_nameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(workLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dateLabel)
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(project_nameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_project_name))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(workCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_work))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dayCombo)
                                    .addComponent(monthCombo)
                                    .addComponent(yearCombo)
                                    .addComponent(label_date))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(group_labour_chargesLabel)
                                    .addComponent(single_labour_chargesLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(wageLabel)
                                            .addComponent(nameLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(wageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(wageTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(wageTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nameCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wageTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nameCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wageTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(extra_expenseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(extra_expenseLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(detailsLabel)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(label_total)
                                            .addComponent(totalLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(maleLabel)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(mnoLabel)
                                            .addComponent(mnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mwageLabel)
                                            .addComponent(mwageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addComponent(femaleLabel)
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(fnoLabel)
                                            .addComponent(fnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fwageLabel)
                                            .addComponent(fwageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(18, 18, 18)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void project_nameComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_project_nameComboFocusGained

    label_project_name.setText("");
    
    // TODO add your handling code here:
}//GEN-LAST:event_project_nameComboFocusGained

private void project_nameComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_project_nameComboFocusLost

    if(project_nameCombo.getSelectedItem().equals("Select"))
    {
        label_project_name.setText("Select a Project Name");
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_project_nameComboFocusLost

private void workComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workComboFocusGained

    label_work.setText("");
    
    // TODO add your handling code here:
}//GEN-LAST:event_workComboFocusGained

private void workComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workComboFocusLost

    if(workCombo.getSelectedItem().equals("Select"))
    {
        label_work.setText("Select a Work");
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_workComboFocusLost

private void yearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboActionPerformed

    if(!dayCombo.getSelectedItem().equals("--")
            && !monthCombo.getSelectedItem().equals("--")
            && !yearCombo.getSelectedItem().equals("----"))
    {
        label_date.setText("");
    }
    else if(dayCombo.getSelectedItem().equals("--")
            || monthCombo.getSelectedItem().equals("--")
            || yearCombo.getSelectedItem().equals("----"))
    {
        label_date.setText("Invalid Date");
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_yearComboActionPerformed

private void monthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboActionPerformed

    if(!dayCombo.getSelectedItem().equals("--")
            && !monthCombo.getSelectedItem().equals("--")
            && !yearCombo.getSelectedItem().equals("----"))
    {
        label_date.setText("");
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_monthComboActionPerformed

private void dayComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayComboActionPerformed

    if(!dayCombo.getSelectedItem().equals("--")
            && !monthCombo.getSelectedItem().equals("--")
            && !yearCombo.getSelectedItem().equals("----"))
    {
        label_date.setText("");
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_dayComboActionPerformed

private void yearComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearComboFocusLost

    if(dayCombo.getSelectedItem().equals("--")
            || monthCombo.getSelectedItem().equals("--")
            || yearCombo.getSelectedItem().equals("----"))
    {
        label_date.setText("Invalid Date");
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_yearComboFocusLost

private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

    if((project_nameCombo.getSelectedItem().equals("Select")
            || workCombo.getSelectedItem().equals("Select")
            || (dayCombo.getSelectedItem().equals("--")
            || monthCombo.getSelectedItem().equals("--")
            || yearCombo.getSelectedItem().equals("----")))
            || ((nameCombo.getSelectedItem().equals("Select")
            || wageTextField.getText().equals(""))
            && ((mnoTextField.getText().equals("")
            || mwageTextField.getText().equals(""))
            && (fnoTextField.getText().equals("")
            || fwageTextField.getText().equals("")))))
    {
        JOptionPane.showMessageDialog(null,"Enter All Appropriate Field");
    }
    else
    {
        JOptionPane.showMessageDialog(null,"Done");
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_addButtonActionPerformed

private void nameComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameComboItemStateChanged

    if(nameCombo.getSelectedItem().equals("Select"))
    {
//        nameCombo1.setVisible(false);
//        wageTextField1.setVisible(false);
//        nameCombo2.setVisible(false);
//        wageTextField2.setVisible(false);
//        nameCombo3.setVisible(false);
//        wageTextField3.setVisible(false);
//        nameCombo4.setVisible(false);
//        wageTextField4.setVisible(false);
    }
    else
    {
        nameCombo1.setVisible(true);
        wageTextField1.setVisible(true);
    }
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_nameComboItemStateChanged

private void nameCombo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameCombo1ItemStateChanged

    if(nameCombo1.getSelectedItem().equals("Select"))
    {
//        nameCombo2.setVisible(false);
//        wageTextField2.setVisible(false);
//        nameCombo3.setVisible(false);
//        wageTextField3.setVisible(false);
//        nameCombo4.setVisible(false);
//        wageTextField4.setVisible(false);
    }
    else
    {
        nameCombo2.setVisible(true);
        wageTextField2.setVisible(true);
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_nameCombo1ItemStateChanged

private void nameCombo2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameCombo2ItemStateChanged

    if(nameCombo2.getSelectedItem().equals("Select"))
    {
//        nameCombo3.setVisible(false);
//        wageTextField3.setVisible(false);
//        nameCombo4.setVisible(false);
//        wageTextField4.setVisible(false);
    }
    else
    {
        nameCombo3.setVisible(true);
        wageTextField3.setVisible(true);
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_nameCombo2ItemStateChanged

private void nameCombo3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameCombo3ItemStateChanged

    if(nameCombo3.getSelectedItem().equals("Select"))
    {
//        nameCombo4.setVisible(false);
//        wageTextField4.setVisible(false);
    }
    else
    {
        nameCombo4.setVisible(true);
        wageTextField4.setVisible(true);
    }
    
    // TODO add your handling code here:
}//GEN-LAST:event_nameCombo3ItemStateChanged

    private void nameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LabourDailyCharges().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox dayCombo;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JLabel detailsLabel1;
    private javax.swing.JTextArea detailsTextArea;
    private javax.swing.JTextArea detailsTextArea1;
    private javax.swing.JLabel extra_expenseLabel;
    private javax.swing.JLabel extra_expenseLabel1;
    private javax.swing.JTextField extra_expenseTextField;
    private javax.swing.JTextField extra_expenseTextField1;
    private javax.swing.JLabel femaleLabel;
    private javax.swing.JLabel fnoLabel;
    private javax.swing.JTextField fnoTextField;
    private javax.swing.JLabel fwageLabel;
    private javax.swing.JTextField fwageTextField;
    private javax.swing.JLabel group_labour_chargesLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_project_name;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel label_total1;
    private javax.swing.JLabel label_work;
    private javax.swing.JLabel labour_daily_chargesLabel;
    private javax.swing.JLabel maleLabel;
    private javax.swing.JLabel mnoLabel;
    private javax.swing.JTextField mnoTextField;
    private javax.swing.JComboBox monthCombo;
    private javax.swing.JLabel mwageLabel;
    private javax.swing.JTextField mwageTextField;
    private javax.swing.JComboBox nameCombo;
    private javax.swing.JComboBox nameCombo1;
    private javax.swing.JComboBox nameCombo2;
    private javax.swing.JComboBox nameCombo3;
    private javax.swing.JComboBox nameCombo4;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox project_nameCombo;
    private javax.swing.JLabel project_nameLabel;
    private javax.swing.JLabel single_labour_chargesLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalLabel1;
    private javax.swing.JLabel wageLabel;
    private javax.swing.JTextField wageTextField;
    private javax.swing.JTextField wageTextField1;
    private javax.swing.JTextField wageTextField2;
    private javax.swing.JTextField wageTextField3;
    private javax.swing.JTextField wageTextField4;
    private javax.swing.JComboBox workCombo;
    private javax.swing.JLabel workLabel;
    private javax.swing.JComboBox yearCombo;
    // End of variables declaration//GEN-END:variables
}
