/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OtherLabourDailyCharges.java
 *
 * Created on Mar 6, 2013, 12:04:42 PM
 */
package pos;
import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Home
 */
public class OtherLabourDailyCharges extends javax.swing.JFrame {
    
    Double ap, mno, mwage, hno, hwage, rpu, tnou, total, total1, total2;
    int wid =0;

    /** Creates new form OtherLabourDailyCharges */
    public OtherLabourDailyCharges() {
        initComponents();
        
        setTitle("Other Labour Daily Charges");
        setSize(660,770);
        setVisible(true);
        setLocation(284,45);
        getContentPane().setBackground(new Color(129,134,138)); 
        
        wage_wisePanel.setVisible(false);
        unit_wisePanel.setVisible(false);
        fixed_amountPanel.setVisible(false);
        
        Functions.FillCombo(project_nameCombo, "PRONAME", "Project");
        Functions.FillCombo(head_of_contractCombo, "contractor", "contractor");
        Functions.FillCombo(select_workCombo, "WORK", "Names");
         AutoCompleteDecorator.decorate(select_workCombo);
        AutoCompleteDecorator.decorate(project_nameCombo);
         AutoCompleteDecorator.decorate(head_of_contractCombo);
        
         try{   Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                Connection con = DriverManager.getConnection("jdbc:odbc:indlands","","");
                Statement  st = con.createStatement();
                  ResultSet res = st.executeQuery("select Work_Id from LabourdailyOther order by Work_Id asc");
                  Boolean rec = res.next();
                  System.out.println("connected successfully");
                  
                  do
                  {
                     if(rec==true) {
                     wid =res.getInt(1);
                      }
                  }while (res.next());
                  
                  wid+=1 ; 
             }
               catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,"58"+e);
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"63"+e);
                System.out.println(e.getMessage());
            }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labour_daily_chargesLabel = new javax.swing.JLabel();
        head_of_contractLabel = new javax.swing.JLabel();
        project_nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        amount_paidLabel = new javax.swing.JLabel();
        project_nameCombo = new javax.swing.JComboBox();
        date = new org.jdesktop.swingx.JXDatePicker();
        select_workCombo = new javax.swing.JComboBox();
        select_workLabel = new javax.swing.JLabel();
        unit_wiseButton = new javax.swing.JRadioButton();
        fixed_amountButton = new javax.swing.JRadioButton();
        wage_wiseButton = new javax.swing.JRadioButton();
        wage_wisePanel = new javax.swing.JPanel();
        mesonsLabel = new javax.swing.JLabel();
        helpersLabel = new javax.swing.JLabel();
        helpers_noTextField = new javax.swing.JTextField();
        mesons_noTextField = new javax.swing.JTextField();
        mesons_wageTextField = new javax.swing.JTextField();
        helpers_wageTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mesons_cashLabel = new javax.swing.JLabel();
        helpers_cashLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        unit_wisePanel = new javax.swing.JPanel();
        rate_per_unitLabel = new javax.swing.JLabel();
        total_unitLabel = new javax.swing.JLabel();
        rate_per_unitTextField = new javax.swing.JTextField();
        total_unitTextField = new javax.swing.JTextField();
        total_cashLabel = new javax.swing.JLabel();
        fixed_amountPanel = new javax.swing.JPanel();
        fixed_amountLabel = new javax.swing.JLabel();
        fixed_amountTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        head_of_contractCombo = new javax.swing.JComboBox();
        amountpaidLabel = new javax.swing.JLabel();
        addButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        labour_daily_chargesLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labour_daily_chargesLabel.setForeground(new java.awt.Color(0, 102, 102));
        labour_daily_chargesLabel.setText("Contractor work update");

        head_of_contractLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        head_of_contractLabel.setText("Head of Contract");

        project_nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        project_nameLabel.setText("Project Name");

        dateLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        dateLabel.setText("Date ");

        amount_paidLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        amount_paidLabel.setText("Amount Paid");

        project_nameCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        project_nameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        project_nameCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                project_nameComboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                project_nameComboFocusLost(evt);
            }
        });

        select_workCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        select_workCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        select_workCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                select_workComboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                select_workComboFocusLost(evt);
            }
        });

        select_workLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        select_workLabel.setText("Select Work");

        buttonGroup1.add(unit_wiseButton);
        unit_wiseButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        unit_wiseButton.setText("Unit Wise");
        unit_wiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unit_wiseButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(fixed_amountButton);
        fixed_amountButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fixed_amountButton.setText("Fixed Amount");
        fixed_amountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixed_amountButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(wage_wiseButton);
        wage_wiseButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        wage_wiseButton.setText("Wage Wise");
        wage_wiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wage_wiseButtonActionPerformed(evt);
            }
        });

        wage_wisePanel.setBackground(new java.awt.Color(129, 134, 138));

        mesonsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mesonsLabel.setText("Mesons");

        helpersLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        helpersLabel.setText("Helpers");

        helpers_noTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                helpers_noTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                helpers_noTextFieldFocusLost(evt);
            }
        });
        helpers_noTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                helpers_noTextFieldKeyReleased(evt);
            }
        });

        mesons_noTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mesons_noTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mesons_noTextFieldFocusLost(evt);
            }
        });
        mesons_noTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mesons_noTextFieldKeyReleased(evt);
            }
        });

        mesons_wageTextField.setEnabled(false);
        mesons_wageTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mesons_wageTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mesons_wageTextFieldFocusLost(evt);
            }
        });
        mesons_wageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mesons_wageTextFieldKeyReleased(evt);
            }
        });

        helpers_wageTextField.setEnabled(false);
        helpers_wageTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                helpers_wageTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                helpers_wageTextFieldFocusLost(evt);
            }
        });
        helpers_wageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                helpers_wageTextFieldKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Wage");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("No");

        mesons_cashLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        mesons_cashLabel.setForeground(new java.awt.Color(255, 0, 0));
        mesons_cashLabel.setText("Cash");

        helpers_cashLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        helpers_cashLabel.setForeground(new java.awt.Color(255, 0, 0));
        helpers_cashLabel.setText("Cash");

        javax.swing.GroupLayout wage_wisePanelLayout = new javax.swing.GroupLayout(wage_wisePanel);
        wage_wisePanel.setLayout(wage_wisePanelLayout);
        wage_wisePanelLayout.setHorizontalGroup(
            wage_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wage_wisePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wage_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesonsLabel)
                    .addComponent(helpersLabel))
                .addGap(51, 51, 51)
                .addGroup(wage_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wage_wisePanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3))
                    .addGroup(wage_wisePanelLayout.createSequentialGroup()
                        .addGroup(wage_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(helpers_noTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesons_noTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(wage_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(helpers_wageTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesons_wageTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(wage_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesons_cashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helpers_cashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        wage_wisePanelLayout.setVerticalGroup(
            wage_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wage_wisePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wage_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wage_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesons_noTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesons_wageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesons_cashLabel)
                    .addComponent(mesonsLabel))
                .addGap(6, 6, 6)
                .addGroup(wage_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpers_noTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpers_wageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpers_cashLabel)
                    .addComponent(helpersLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        unit_wisePanel.setBackground(new java.awt.Color(129, 134, 138));

        rate_per_unitLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        rate_per_unitLabel.setText("Rate per Unit");

        total_unitLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        total_unitLabel.setText("Total no:of Unit");

        rate_per_unitTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rate_per_unitTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rate_per_unitTextFieldFocusLost(evt);
            }
        });
        rate_per_unitTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rate_per_unitTextFieldKeyReleased(evt);
            }
        });

        total_unitTextField.setEnabled(false);
        total_unitTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                total_unitTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                total_unitTextFieldFocusLost(evt);
            }
        });
        total_unitTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                total_unitTextFieldKeyReleased(evt);
            }
        });

        total_cashLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        total_cashLabel.setForeground(new java.awt.Color(255, 0, 0));
        total_cashLabel.setText("Cash");

        javax.swing.GroupLayout unit_wisePanelLayout = new javax.swing.GroupLayout(unit_wisePanel);
        unit_wisePanel.setLayout(unit_wisePanelLayout);
        unit_wisePanelLayout.setHorizontalGroup(
            unit_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unit_wisePanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(unit_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rate_per_unitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(total_unitLabel))
                .addGap(37, 37, 37)
                .addGroup(unit_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_cashLabel)
                    .addGroup(unit_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(total_unitTextField)
                        .addComponent(rate_per_unitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        unit_wisePanelLayout.setVerticalGroup(
            unit_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, unit_wisePanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(unit_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rate_per_unitLabel)
                    .addComponent(rate_per_unitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(unit_wisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_unitLabel)
                    .addComponent(total_unitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(total_cashLabel)
                .addContainerGap())
        );

        fixed_amountPanel.setBackground(new java.awt.Color(129, 134, 138));

        fixed_amountLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fixed_amountLabel.setText("Fixed Amount");

        fixed_amountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fixed_amountTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fixed_amountTextFieldFocusLost(evt);
            }
        });
        fixed_amountTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fixed_amountTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout fixed_amountPanelLayout = new javax.swing.GroupLayout(fixed_amountPanel);
        fixed_amountPanel.setLayout(fixed_amountPanelLayout);
        fixed_amountPanelLayout.setHorizontalGroup(
            fixed_amountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fixed_amountPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(fixed_amountLabel)
                .addGap(32, 32, 32)
                .addComponent(fixed_amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fixed_amountPanelLayout.setVerticalGroup(
            fixed_amountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fixed_amountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fixed_amountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixed_amountLabel)
                    .addComponent(fixed_amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        head_of_contractCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        head_of_contractCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        head_of_contractCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                head_of_contractComboItemStateChanged(evt);
            }
        });
        head_of_contractCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                head_of_contractComboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                head_of_contractComboFocusLost(evt);
            }
        });

        amountpaidLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        amountpaidLabel.setText("No payment");

        addButton1.setText("Cancel");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(select_workLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(select_workCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(unit_wiseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(177, 177, 177))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fixed_amountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(143, 143, 143))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(wage_wiseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(163, 163, 163)))))
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fixed_amountPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unit_wisePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wage_wisePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(head_of_contractLabel)
                                .addComponent(project_nameLabel)
                                .addComponent(dateLabel)
                                .addComponent(amount_paidLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(project_nameCombo, 0, 134, Short.MAX_VALUE)
                                .addComponent(head_of_contractCombo, 0, 134, Short.MAX_VALUE)
                                .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(amountpaidLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(labour_daily_chargesLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labour_daily_chargesLabel)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(project_nameLabel)
                    .addComponent(project_nameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(head_of_contractLabel)
                        .addComponent(head_of_contractCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_paidLabel)
                    .addComponent(amountpaidLabel))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_workLabel)
                    .addComponent(select_workCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(wage_wiseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_wiseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fixed_amountButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wage_wisePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit_wisePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fixed_amountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void unit_wiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unit_wiseButtonActionPerformed

    wage_wiseButton.setForeground(Color.black);
    unit_wiseButton.setForeground(Color.black);
    fixed_amountButton.setForeground(Color.black);
    
    mesons_noTextField.setBackground(Color.white);
    mesons_noTextField.setText("");
    mesons_wageTextField.setText("");
    mesons_wageTextField.setEnabled(false);
    helpers_noTextField.setBackground(Color.white);
    helpers_noTextField.setText("");
    helpers_wageTextField.setText("");
    helpers_wageTextField.setEnabled(false);
    
    fixed_amountTextField.setText("");
    fixed_amountTextField.setBackground(Color.white);
    
    unit_wisePanel.setVisible(true);
    wage_wisePanel.setVisible(false);
    fixed_amountPanel.setVisible(false);
    
    // TODO add your handling code here:
}//GEN-LAST:event_unit_wiseButtonActionPerformed

private void fixed_amountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixed_amountButtonActionPerformed

    wage_wiseButton.setForeground(Color.black);
    unit_wiseButton.setForeground(Color.black);
    fixed_amountButton.setForeground(Color.black);
    
    mesons_noTextField.setBackground(Color.white);
    mesons_noTextField.setText("");
    mesons_wageTextField.setText("");
    mesons_wageTextField.setEnabled(false);
    helpers_noTextField.setBackground(Color.white);
    helpers_noTextField.setText("");
    helpers_wageTextField.setText("");
    helpers_wageTextField.setEnabled(false);
    
    rate_per_unitTextField.setBackground(Color.white);
    total_unitTextField.setEnabled(false);
    rate_per_unitTextField.setText("");
    total_unitTextField.setText("");
    
    fixed_amountPanel.setVisible(true);
    unit_wisePanel.setVisible(false);
    wage_wisePanel.setVisible(false);
    
    // TODO add your handling code here:
}//GEN-LAST:event_fixed_amountButtonActionPerformed

    private void project_nameComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_project_nameComboFocusLost

        if(project_nameCombo.getSelectedItem().equals("Select"))
        {
            project_nameLabel.setForeground(Color.red);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_project_nameComboFocusLost

    private void project_nameComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_project_nameComboFocusGained

        project_nameLabel.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_project_nameComboFocusGained

    private void mesons_noTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesons_noTextFieldKeyReleased

        if(Functions.NumericValidate(mesons_noTextField))
        {
            mesons_wageTextField.setBackground(Color.white);
            
            if(mesons_noTextField.getText().equals(""))
            {
                mno=0.0;
                mesons_wageTextField.setEnabled(false);
            }
            if(mesons_wageTextField.getText().equals(""))
            {
                mwage=0.0;
            }
            if(!mesons_noTextField.getText().equals(""))
            {
                mno = Double.parseDouble(mesons_noTextField.getText());
                mesons_wageTextField.setEnabled(true);
            }
            if(!mesons_wageTextField.getText().equals(""))
            {
                mwage = Double.parseDouble(mesons_wageTextField.getText());
            }
            total = mno * mwage;
            mesons_cashLabel.setText(Double.toString(total));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mesons_noTextFieldKeyReleased

    private void mesons_wageTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesons_wageTextFieldKeyReleased

        if(Functions.NumericValidate(mesons_wageTextField))
        {
            if(helpers_noTextField.getText().equals("") && helpers_wageTextField.getText().equals(""))
            {
                helpers_noTextField.setBackground(Color.white);
            }
            
            if(mesons_noTextField.getText().equals(""))
            {
                mno=0.0;
            }
            if(mesons_wageTextField.getText().equals(""))
            {
                mwage=0.0;
            }
            if(!mesons_noTextField.getText().equals(""))
            {
                mno = Double.parseDouble(mesons_noTextField.getText());
            }
            if(!mesons_wageTextField.getText().equals(""))
            {
                mwage = Double.parseDouble(mesons_wageTextField.getText());
            }
            total = mno * mwage;
            mesons_cashLabel.setText(Double.toString(total));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mesons_wageTextFieldKeyReleased

    private void helpers_noTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_helpers_noTextFieldKeyReleased

        if(Functions.NumericValidate(helpers_noTextField))
        {
            helpers_wageTextField.setBackground(Color.white);
            
            if(helpers_noTextField.getText().equals(""))
            {
                hno=0.0;
                helpers_wageTextField.setEnabled(false);
            }
            if(helpers_wageTextField.getText().equals(""))
            {
                hwage=0.0;
            }
            if(!helpers_noTextField.getText().equals(""))
            {
                hno = Double.parseDouble(helpers_noTextField.getText());
                helpers_wageTextField.setEnabled(true);
            }
            if(!helpers_wageTextField.getText().equals(""))
            {
                hwage = Double.parseDouble(helpers_wageTextField.getText());
            }
            total1 = hno * hwage;
            helpers_cashLabel.setText(Double.toString(total1));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_helpers_noTextFieldKeyReleased

    private void helpers_wageTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_helpers_wageTextFieldKeyReleased

        if(Functions.NumericValidate(helpers_noTextField))
        {
            if(mesons_noTextField.getText().equals("") && mesons_wageTextField.getText().equals(""))
            {
                mesons_noTextField.setBackground(Color.white);
            }
            
            if(helpers_noTextField.getText().equals(""))
            {
                hno=0.0;
            }
            if(helpers_wageTextField.getText().equals(""))
            {
                hwage=0.0;
            }
            if(!helpers_noTextField.getText().equals(""))
            {
                hno = Double.parseDouble(helpers_noTextField.getText());
            }
            if(!helpers_wageTextField.getText().equals(""))
            {
                hwage = Double.parseDouble(helpers_wageTextField.getText());
            }
            total1 = hno * hwage;
            helpers_cashLabel.setText(Double.toString(total1));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_helpers_wageTextFieldKeyReleased

    private void rate_per_unitTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rate_per_unitTextFieldKeyReleased

        if(Functions.NumericValidate(rate_per_unitTextField))
        {
            total_unitTextField.setBackground(Color.white);
            
            if(rate_per_unitTextField.getText().equals(""))
            {
                rpu=0.0;
                total_unitTextField.setEnabled(false);
            }
            if(total_unitTextField.getText().equals(""))
            {
                tnou=0.0;
            }
            if(!rate_per_unitTextField.getText().equals(""))
            {
                rpu = Double.parseDouble(rate_per_unitTextField.getText());
                total_unitTextField.setEnabled(true);
            }
            if(!total_unitTextField.getText().equals(""))
            {
                tnou = Double.parseDouble(total_unitTextField.getText());
            }
            total2 = rpu * tnou;
            total_cashLabel.setText(Double.toString(total2));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_rate_per_unitTextFieldKeyReleased

    private void total_unitTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_unitTextFieldKeyReleased

        if(Functions.NumericValidate(rate_per_unitTextField))
        {
            if(rate_per_unitTextField.getText().equals(""))
            {
                rpu=0.0;
            }
            if(total_unitTextField.getText().equals(""))
            {
                tnou=0.0;
            }
            if(!rate_per_unitTextField.getText().equals(""))
            {
                rpu = Double.parseDouble(rate_per_unitTextField.getText());
            }
            if(!total_unitTextField.getText().equals(""))
            {
                tnou = Double.parseDouble(total_unitTextField.getText());
            }
            total2 = rpu * tnou;
            total_cashLabel.setText(Double.toString(total2));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_total_unitTextFieldKeyReleased

    private void fixed_amountTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fixed_amountTextFieldKeyReleased

        Functions.NumericValidation(fixed_amountTextField);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_fixed_amountTextFieldKeyReleased

    private void select_workComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_select_workComboFocusGained

        select_workLabel.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_select_workComboFocusGained

    private void select_workComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_select_workComboFocusLost

        if(select_workCombo.getSelectedItem().equals("Select"))
        {
            select_workLabel.setForeground(Color.red);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_select_workComboFocusLost

    private void mesons_noTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mesons_noTextFieldFocusGained

        mesons_noTextField.setBackground(Color.white);
        if(!helpers_noTextField.getText().equals("") && helpers_wageTextField.getText().equals(""))
        {
            helpers_wageTextField.setBackground(Color.pink);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mesons_noTextFieldFocusGained

    private void mesons_noTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mesons_noTextFieldFocusLost

        if(mesons_noTextField.getText().equals("") && !mesons_wageTextField.getText().equals(""))
        {
            mesons_noTextField.setBackground(Color.pink);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mesons_noTextFieldFocusLost

    private void mesons_wageTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mesons_wageTextFieldFocusGained

        mesons_wageTextField.setBackground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mesons_wageTextFieldFocusGained

    private void mesons_wageTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mesons_wageTextFieldFocusLost

        if(!mesons_noTextField.getText().equals("") && mesons_wageTextField.getText().equals(""))
        {
            mesons_wageTextField.setBackground(Color.pink);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mesons_wageTextFieldFocusLost

    private void helpers_noTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_helpers_noTextFieldFocusGained

        helpers_noTextField.setBackground(Color.white);
        if(!mesons_noTextField.getText().equals("") && mesons_wageTextField.getText().equals(""))
        {
            mesons_wageTextField.setBackground(Color.pink);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_helpers_noTextFieldFocusGained

    private void helpers_noTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_helpers_noTextFieldFocusLost

        if(helpers_noTextField.getText().equals("") && !helpers_wageTextField.getText().equals(""))
        {
            helpers_noTextField.setBackground(Color.pink);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_helpers_noTextFieldFocusLost

    private void helpers_wageTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_helpers_wageTextFieldFocusGained

        helpers_wageTextField.setBackground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_helpers_wageTextFieldFocusGained

    private void helpers_wageTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_helpers_wageTextFieldFocusLost

        if(!helpers_noTextField.getText().equals("") && helpers_wageTextField.getText().equals(""))
        {
            helpers_wageTextField.setBackground(Color.pink);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_helpers_wageTextFieldFocusLost

    private void rate_per_unitTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rate_per_unitTextFieldFocusGained

        rate_per_unitTextField.setBackground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_rate_per_unitTextFieldFocusGained

    private void rate_per_unitTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rate_per_unitTextFieldFocusLost

        if(rate_per_unitTextField.getText().equals("") && !total_unitTextField.getText().equals(""))
        {
            rate_per_unitTextField.setBackground(Color.pink);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_rate_per_unitTextFieldFocusLost

    private void total_unitTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_unitTextFieldFocusGained

        total_unitTextField.setBackground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_total_unitTextFieldFocusGained

    private void total_unitTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_unitTextFieldFocusLost

        if(!rate_per_unitTextField.getText().equals("") && total_unitTextField.getText().equals(""))
        {
            total_unitTextField.setBackground(Color.pink);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_total_unitTextFieldFocusLost

    private void fixed_amountTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fixed_amountTextFieldFocusGained

        fixed_amountTextField.setBackground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_fixed_amountTextFieldFocusGained

    private void fixed_amountTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fixed_amountTextFieldFocusLost

        if(fixed_amountTextField.getText().equals(""))
        {
            fixed_amountTextField.setBackground(Color.pink);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_fixed_amountTextFieldFocusLost

    private void wage_wiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wage_wiseButtonActionPerformed

        wage_wiseButton.setForeground(Color.black);
        unit_wiseButton.setForeground(Color.black);
        fixed_amountButton.setForeground(Color.black);
        
        rate_per_unitTextField.setBackground(Color.white);
        total_unitTextField.setEnabled(false);
        rate_per_unitTextField.setText("");
        total_unitTextField.setText("");
        
        fixed_amountTextField.setBackground(Color.white);
        fixed_amountTextField.setText("");
        
        wage_wisePanel.setVisible(true);
        unit_wisePanel.setVisible(false);
        fixed_amountPanel.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_wage_wiseButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        String  pname = (String) project_nameCombo.getSelectedItem();
        String hoc    = (String)head_of_contractCombo.getSelectedItem();
        String work   = (String)select_workCombo.getSelectedItem();
        int flag = 0;
        String butvalue = "";
        
        if(project_nameCombo.getSelectedItem().equals("Select"))
        {
            project_nameLabel.setForeground(Color.red);
            flag++;
        }
        


        if (date.getEditor().getText().equals("") )
        {
        dateLabel.setForeground(Color.red); 
        
        }
        if(head_of_contractCombo.getSelectedItem().equals("Select"))
        {
            head_of_contractLabel.setForeground(Color.red);
            flag++;
        }
        
        // DATE VALIDATION GO HERE ------------------ //
        
        if(select_workCombo.getSelectedItem().equals("Select"))
        {
            select_workLabel.setForeground(Color.red);
            flag++;
        }
        
        // Three Radio Button Validation 
        
        if(!wage_wiseButton.isSelected() && !unit_wiseButton.isSelected() && !fixed_amountButton.isSelected())
        {
            flag++;
            wage_wiseButton.setForeground(Color.red);
            unit_wiseButton.setForeground(Color.red);
            fixed_amountButton.setForeground(Color.red);
        }
        
        Enumeration<AbstractButton> allRadioButton=buttonGroup1.getElements(); 
        while(allRadioButton.hasMoreElements())
        {
            JRadioButton temp =(JRadioButton)allRadioButton.nextElement();
            if (temp.isSelected())
            {
                if(temp.getText().equals("Wage Wise"))
                {    butvalue = temp.getText(); 
                    if((mesons_noTextField.getText().equals("") && mesons_wageTextField.getText().equals(""))
                            && (helpers_noTextField.getText().equals("") && helpers_wageTextField.getText().equals("")))
                    {
                        mesons_noTextField.setBackground(Color.pink);
                        helpers_noTextField.setBackground(Color.pink);
                        flag++;
                    }
                    if(mesons_noTextField.getText().equals("") && !mesons_wageTextField.getText().equals(""))
                    {
                        mesons_noTextField.setBackground(Color.pink);
                        flag++;
                    }
                    if(!mesons_noTextField.getText().equals("") && mesons_wageTextField.getText().equals(""))
                    {
                        mesons_wageTextField.setBackground(Color.pink);
                        flag++;
                    }
                    if(helpers_noTextField.getText().equals("") && !helpers_wageTextField.getText().equals(""))
                    {
                        helpers_noTextField.setBackground(Color.pink);
                        flag++;
                    }
                    if(!helpers_noTextField.getText().equals("") && helpers_wageTextField.getText().equals(""))
                    {
                        helpers_wageTextField.setBackground(Color.pink);
                        flag++;
                    }
                }
                else if(temp.getText().equals("Unit Wise"))
                {  butvalue = temp.getText(); 
                    if(rate_per_unitTextField.getText().equals("") && total_unitTextField.getText().equals(""))
                    {
                        rate_per_unitTextField.setBackground(Color.pink);
                        total_unitTextField.setBackground(Color.pink);
                        flag++;
                    }
                    if(rate_per_unitTextField.getText().equals("") && !total_unitTextField.getText().equals(""))
                    {
                        rate_per_unitTextField.setBackground(Color.pink);
                        flag++;
                    }
                    if(!rate_per_unitTextField.getText().equals("") && total_unitTextField.getText().equals(""))
                    {
                        total_unitTextField.setBackground(Color.pink);
                        flag++;
                    }
                }
                else if(temp.getText().equals("Fixed Amount"))
                {    butvalue = temp.getText(); 
                    if(fixed_amountTextField.getText().equals(""))
                    {
                        fixed_amountTextField.setBackground(Color.pink);
                        flag++;
                    }
                }
            }
        }
        
        // Radio Button Validations End
        
        // Code for DataBase Starts Here
        
        if(flag==0)
        {
            int units=0 ,unitrate=0, meson=0,mesonwage=0,helper=0,helperwage=0,tot=0;
            //String abc = temp.getText();
            //JOptionPane.showMessageDialog(null,"Done :)" +butvalue);
            if ("Unit Wise".equals(butvalue))
            {
                unitrate  = Integer.parseInt( rate_per_unitTextField.getText());
                units= Integer.parseInt(total_unitTextField.getText());
                tot = unitrate*units ;
                //JOptionPane.showMessageDialog(null,"Yeah thats right11!!");
                
                
            }
             if ("Wage Wise".equals(butvalue))
            {
                meson     = Integer.parseInt(mesons_noTextField.getText());
                mesonwage = Integer.parseInt(mesons_wageTextField.getText());
                helper    = Integer.parseInt(helpers_noTextField.getText());
                helperwage= Integer.parseInt(helpers_wageTextField.getText());
                tot =   (meson*mesonwage)+(helper*helperwage);
                //JOptionPane.showMessageDialog(null,"Yeah thats right22!!");
            }
              if ("Fixed Amount".equals(butvalue))
            {
                
                  tot = Integer.parseInt(fixed_amountTextField.getText());
                //JOptionPane.showMessageDialog(null,"Yeah thats right33!!");
            }
             
              if((wage_wiseButton.isSelected())||(unit_wiseButton.isSelected())||(fixed_amountButton.isSelected()))
              {
                  try {
                        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                        Connection con = DriverManager.getConnection("jdbc:odbc:indlands","","");
                        
                        SimpleDateFormat formater = new SimpleDateFormat("MM/dd/yyyy");
                       String newdate=    formater.format(date.getDate()); 
                        //java.sql.Date sqlDate = new java.sql.Date(new java.util.Date().getTime());
                        PreparedStatement prp=con.prepareStatement("insert into LabourdailyOther  values(?,?,?,?,?,?,?,?,?,?,?,?,?)");  
                        prp.setInt(1,wid);
                        prp.setString(2,hoc);
                        prp.setString(3,work);  
                        prp.setString(4,butvalue);
                        prp.setInt(5,meson);
                        prp.setInt(6, helper);
                        prp.setInt(7,mesonwage);
                        prp.setInt(8, helperwage);
                        prp.setInt(9,units);
                        prp.setInt(10,unitrate);
                        prp.setInt(11, tot);
                        prp.setString(12, newdate);
                        prp.setString(13, pname);
                        prp.executeUpdate(); 
                       // JOptionPane.showMessageDialog(null,"Details added succesfully");
                         con.commit();
                         con.close();
                         wid+=1;
                         
                         project_nameCombo.setSelectedItem("Select");
                         select_workCombo.setSelectedItem("Select");
                         head_of_contractCombo.setSelectedItem("Select");
                         rate_per_unitTextField.setText("");
                         total_unitTextField.setText("");
                         mesons_noTextField.setText("");
                         mesons_wageTextField.setText("");
                         helpers_noTextField.setText("");
                         helpers_wageTextField.setText("");
                         fixed_amountTextField.setText("");
                         
                  
                  }                               
             catch(SQLException e)
             {JOptionPane.showMessageDialog(null,"1062"+e); }
            catch(Exception e)
            { JOptionPane.showMessageDialog(null,"1064"+e);
            }
                     Functions.DisposeFunc(this);
        } 
      }
    }//GEN-LAST:event_addButtonActionPerformed

    private void head_of_contractComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_head_of_contractComboFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_head_of_contractComboFocusGained

    private void head_of_contractComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_head_of_contractComboFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_head_of_contractComboFocusLost

    private void head_of_contractComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_head_of_contractComboItemStateChanged
        int amount = 0;
        String pname = (String) project_nameCombo.getSelectedItem();
        String contractor = (String) head_of_contractCombo.getSelectedItem();
        try {
                  Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                  Connection con = DriverManager.getConnection("jdbc:odbc:indlands","","");
                  Statement  st = con.createStatement();
                  ResultSet res = st.executeQuery("select SUM(amount) from Payment where category='contractor' and pname= '"+pname+"' and cname='"+contractor+"'  ");
                   Boolean rec = res.next();
                  if (rec==true){
                       amount = res.getInt(1);
                  }
                  else{
                  amount = 0 ;
                  }
                  
                  }
         catch(SQLException e)
             {JOptionPane.showMessageDialog(null,"1035"+e); }
            catch(Exception e)
            { JOptionPane.showMessageDialog(null,"990"+e);
                   }
       String amount1 = Integer.toString(amount);
        amountpaidLabel.setText(amount1);
        
    }//GEN-LAST:event_head_of_contractComboItemStateChanged

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_addButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Contractor c = new Contractor(1,head_of_contractCombo)   ;     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtherLabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtherLabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtherLabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtherLabourDailyCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OtherLabourDailyCharges().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JLabel amount_paidLabel;
    private javax.swing.JLabel amountpaidLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.swingx.JXDatePicker date;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JRadioButton fixed_amountButton;
    private javax.swing.JLabel fixed_amountLabel;
    private javax.swing.JPanel fixed_amountPanel;
    private javax.swing.JTextField fixed_amountTextField;
    private javax.swing.JComboBox head_of_contractCombo;
    private javax.swing.JLabel head_of_contractLabel;
    private javax.swing.JLabel helpersLabel;
    private javax.swing.JLabel helpers_cashLabel;
    private javax.swing.JTextField helpers_noTextField;
    private javax.swing.JTextField helpers_wageTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labour_daily_chargesLabel;
    private javax.swing.JLabel mesonsLabel;
    private javax.swing.JLabel mesons_cashLabel;
    private javax.swing.JTextField mesons_noTextField;
    private javax.swing.JTextField mesons_wageTextField;
    private javax.swing.JComboBox project_nameCombo;
    private javax.swing.JLabel project_nameLabel;
    private javax.swing.JLabel rate_per_unitLabel;
    private javax.swing.JTextField rate_per_unitTextField;
    private javax.swing.JComboBox select_workCombo;
    private javax.swing.JLabel select_workLabel;
    private javax.swing.JLabel total_cashLabel;
    private javax.swing.JLabel total_unitLabel;
    private javax.swing.JTextField total_unitTextField;
    private javax.swing.JRadioButton unit_wiseButton;
    private javax.swing.JPanel unit_wisePanel;
    private javax.swing.JRadioButton wage_wiseButton;
    private javax.swing.JPanel wage_wisePanel;
    // End of variables declaration//GEN-END:variables
}
