/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author lenovo
 */
public class Plan extends javax.swing.JFrame {
 int Charge , Expense=0,Total;
    /**
     * Creates new form Plan
     */
    public Plan() {
        initComponents();
        setTitle("Plan");
        setLocation(238,0);
        setSize(660,500);
        getContentPane().setBackground(new Color(129,134,138));
        setVisible(true);
        Functions.FillCombo(detailsCombo, "plan", "Names");
        AutoCompleteDecorator.decorate(detailsCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalLabel = new javax.swing.JLabel();
        chargeLabel = new javax.swing.JLabel();
        detailsLabel = new javax.swing.JLabel();
        expenseLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        chargeTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        planLabel = new javax.swing.JLabel();
        expenseTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        cashLabel = new javax.swing.JLabel();
        detailsCombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        totalLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalLabel.setText("Total");

        chargeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        chargeLabel.setText("Charge");

        detailsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        detailsLabel.setText("Work Details");

        expenseLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        expenseLabel.setText("Extra Expenses");

        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });

        chargeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chargeTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                chargeTextFieldFocusLost(evt);
            }
        });
        chargeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chargeTextFieldKeyReleased(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nameLabel.setText("Client Name");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        planLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        planLabel.setForeground(new java.awt.Color(0, 102, 102));
        planLabel.setText("Plan / Design ");

        expenseTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                expenseTextFieldFocusGained(evt);
            }
        });
        expenseTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                expenseTextFieldKeyReleased(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        cashLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cashLabel.setForeground(new java.awt.Color(255, 0, 0));
        cashLabel.setText("Cash");

        detailsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(planLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detailsLabel)
                                    .addComponent(nameLabel)
                                    .addComponent(chargeLabel))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(detailsCombo, 0, 173, Short.MAX_VALUE)
                                            .addComponent(nameTextField))
                                        .addGap(50, 50, 50)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(expenseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(expenseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(totalLabel)
                        .addGap(36, 36, 36)
                        .addComponent(cashLabel)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(planLabel)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsLabel)
                    .addComponent(detailsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chargeLabel))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expenseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expenseLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(cashLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
       
        int flag = 0;
        
        String Details,Cname;
        
        if(nameTextField.getText().equals(""))
        {
            nameLabel.setForeground(Color.red);
            flag++;
        }
        
        if(chargeTextField.getText().equals(""))
        {
            chargeLabel.setForeground(Color.red);
            flag++;
        }
        if(detailsCombo.getSelectedItem().equals("Select"))
        {
            detailsLabel.setForeground(Color.red);
            flag++;
        }
        if(!expenseTextField.getText().equals(""))
        {
        Expense =Integer.parseInt( expenseTextField.getText());
        }
        else
        {
        Expense=0;
        }
        
        if(flag == 0)
         {  
             Cname= nameTextField.getText();
             Details = (String) detailsCombo.getSelectedItem();
             Charge=Integer.parseInt(chargeTextField.getText());
             
             Total=Charge+Expense;
             
             
              
             try {
             Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                Connection con = DriverManager.getConnection("jdbc:odbc:indlands","","");
                java.sql.Date sqlDate = new java.sql.Date(new java.util.Date().getTime());
                  PreparedStatement prp=con.prepareStatement("insert into Plan(CNAME,WORK,COST,EXTRA,TOTAL,PDATE) values(?,?,?,?,?,?)");    
                                               
                        prp.setString(1,Cname);
                        prp.setString(2,Details);
                        prp.setInt(3,Charge);
                        prp.setInt(4,Expense);
                        prp.setInt(5,Total);
                        prp.setDate(6,sqlDate);
                                            
                        prp.executeUpdate(); 
                        
                        Functions.DisposeFunc(this);
                         
                         nameTextField.setText("");
                         chargeTextField.setText("");
                         expenseTextField.setText("");
                         detailsCombo.setSelectedItem("Select");
                         cashLabel.setText("Cash");
                         cashLabel.setForeground(Color.black);
                         con.commit();
                         con.close();
             }                               
             
             catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,""+e);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"The error is1:"+e);
            }
         }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained

        nameLabel.setForeground(Color.black);
        
    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost

        if(nameTextField.getText().equals(""))
        {
            nameLabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void chargeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chargeTextFieldFocusGained

        chargeLabel.setForeground(Color.black);
        
        if(nameTextField.getText().equals(""))
        {
            nameLabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_chargeTextFieldFocusGained

    private void chargeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chargeTextFieldFocusLost

        if(chargeTextField.getText().equals(""))
        {
            chargeLabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_chargeTextFieldFocusLost

    private void chargeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chargeTextFieldKeyReleased
        
        if(Functions.NumericValidate(chargeTextField))
        {
            if(chargeTextField.getText().equals(""))
            {
                Charge = 0;
            } else Charge = Integer.parseInt(chargeTextField.getText());
            
            if(expenseTextField.getText().equals(""))
            {
                Expense = 0;
            } else Expense = Integer.parseInt(expenseTextField.getText());
            
            Total = Charge + Expense ;
            
            cashLabel.setText(Integer.toString(Total));
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_chargeTextFieldKeyReleased

    private void expenseTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expenseTextFieldFocusGained

        if(nameTextField.getText().equals(""))
        {
            nameLabel.setForeground(Color.red);
        }
        
        if(chargeTextField.getText().equals(""))
        {
            chargeLabel.setForeground(Color.red);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseTextFieldFocusGained

    private void expenseTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expenseTextFieldKeyReleased

        if(Functions.NumericValidate(expenseTextField))
        {
            if(chargeTextField.getText().equals(""))
            {
                Charge = 0;
            } else Charge = Integer.parseInt(chargeTextField.getText());
            
            if(expenseTextField.getText().equals(""))
            {
                Expense = 0;
            } else Expense = Integer.parseInt(expenseTextField.getText());
            
            Total = Charge + Expense ;
            
            cashLabel.setText(Integer.toString(Total));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseTextFieldKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           String worknew =  JOptionPane.showInputDialog(null, "Enter New Work");
        while (worknew.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter new work");
            worknew = JOptionPane.showInputDialog(null, "Enter New Work");
        }
        try{
            
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                Connection con = DriverManager.getConnection("jdbc:odbc:indlands","","");
                 PreparedStatement prp=con.prepareStatement("insert into Names(plan) values(?)");
                 prp.setString(1, worknew);
                 prp.executeUpdate(); 
                 detailsCombo.setSelectedItem(worknew);
                  con.commit();
                  con.close();
        }
         
             catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,"Err is"+e);
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"The error is1:"+e);
             }     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Plan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cashLabel;
    private javax.swing.JLabel chargeLabel;
    private javax.swing.JTextField chargeTextField;
    private javax.swing.JComboBox detailsCombo;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JLabel expenseLabel;
    private javax.swing.JTextField expenseTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel planLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
