/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import java.awt.Color;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author lenovo
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        setLocation(238,0);
//        setLocationRelativeTo(null);
        setSize(660,350);
        setTitle("Reports");
        getContentPane().setBackground(new Color(129,134,138));
        setVisible(true);
        
        Functions.FillCombo(projectCombo,"PRONAME","Project");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        reportsLabel = new javax.swing.JLabel();
        project_nameLabel = new javax.swing.JLabel();
        projectCombo = new javax.swing.JComboBox();
        reportPanel = new javax.swing.JPanel();
        report_typeLabel = new javax.swing.JLabel();
        prButton = new javax.swing.JButton();
        mrButton = new javax.swing.JButton();
        vrButton = new javax.swing.JButton();
        irButton = new javax.swing.JButton();
        crButton = new javax.swing.JButton();
        wrButton = new javax.swing.JButton();
        lrButton = new javax.swing.JButton();
        fromDate = new org.jdesktop.swingx.JXDatePicker();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        toDate = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        reportsLabel.setFont(new java.awt.Font("Times New Roman", 1, 36));
        reportsLabel.setForeground(new java.awt.Color(0, 102, 102));
        reportsLabel.setText("Reports");

        project_nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        project_nameLabel.setText("Project Name");

        projectCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        projectCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        projectCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                projectComboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                projectComboFocusLost(evt);
            }
        });

        reportPanel.setBackground(new java.awt.Color(129, 134, 138));
        reportPanel.setEnabled(false);

        report_typeLabel.setFont(new java.awt.Font("Times New Roman", 1, 24));
        report_typeLabel.setForeground(new java.awt.Color(0, 102, 102));
        report_typeLabel.setText("Report Type");

        prButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        prButton.setText("Project");
        prButton.setBorder(null);
        prButton.setBorderPainted(false);
        prButton.setContentAreaFilled(false);
        prButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prButton.setFocusPainted(false);
        prButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prButtonMouseExited(evt);
            }
        });
        prButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prButtonActionPerformed(evt);
            }
        });

        mrButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
        mrButton.setText("Material");
        mrButton.setBorder(null);
        mrButton.setBorderPainted(false);
        mrButton.setContentAreaFilled(false);
        mrButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mrButton.setFocusPainted(false);
        mrButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mrButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mrButtonMouseExited(evt);
            }
        });
        mrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrButtonActionPerformed(evt);
            }
        });

        vrButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
        vrButton.setText("Vendor");
        vrButton.setBorder(null);
        vrButton.setBorderPainted(false);
        vrButton.setContentAreaFilled(false);
        vrButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vrButton.setFocusPainted(false);
        vrButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vrButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vrButtonMouseExited(evt);
            }
        });
        vrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrButtonActionPerformed(evt);
            }
        });

        irButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
        irButton.setText("Item");
        irButton.setBorder(null);
        irButton.setBorderPainted(false);
        irButton.setContentAreaFilled(false);
        irButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irButton.setFocusPainted(false);
        irButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                irButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                irButtonMouseExited(evt);
            }
        });
        irButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irButtonActionPerformed(evt);
            }
        });

        crButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
        crButton.setText("Customer");
        crButton.setBorder(null);
        crButton.setBorderPainted(false);
        crButton.setContentAreaFilled(false);
        crButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crButton.setFocusPainted(false);
        crButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crButtonMouseExited(evt);
            }
        });
        crButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crButtonActionPerformed(evt);
            }
        });

        wrButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
        wrButton.setText("Work");
        wrButton.setBorder(null);
        wrButton.setBorderPainted(false);
        wrButton.setContentAreaFilled(false);
        wrButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wrButton.setFocusPainted(false);
        wrButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wrButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wrButtonMouseExited(evt);
            }
        });
        wrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrButtonActionPerformed(evt);
            }
        });

        lrButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lrButton.setText("Labour");
        lrButton.setBorder(null);
        lrButton.setBorderPainted(false);
        lrButton.setContentAreaFilled(false);
        lrButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lrButton.setFocusPainted(false);
        lrButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lrButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lrButtonMouseExited(evt);
            }
        });
        lrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lrButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(report_typeLabel))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addComponent(prButton)
                        .addGap(18, 18, 18)
                        .addComponent(vrButton)
                        .addGap(18, 18, 18)
                        .addComponent(wrButton)
                        .addGap(18, 18, 18)
                        .addComponent(crButton)
                        .addGap(18, 18, 18)
                        .addComponent(mrButton)
                        .addGap(18, 18, 18)
                        .addComponent(irButton)
                        .addGap(18, 18, 18)
                        .addComponent(lrButton)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(report_typeLabel)
                .addGap(18, 18, 18)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vrButton)
                    .addComponent(wrButton)
                    .addComponent(crButton)
                    .addComponent(mrButton)
                    .addComponent(prButton)
                    .addComponent(irButton)
                    .addComponent(lrButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fromDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fromDateFocusGained(evt);
            }
        });

        fromLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fromLabel.setText("From");

        toLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        toLabel.setText("To");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(reportsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(project_nameLabel)
                        .addGap(37, 37, 37)
                        .addComponent(projectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fromLabel)
                        .addGap(18, 18, 18)
                        .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(toLabel)
                        .addGap(18, 18, 18)
                        .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportsLabel)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(project_nameLabel))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromLabel)
                    .addComponent(toLabel)
                    .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prButtonMouseEntered

        prButton.setForeground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_prButtonMouseEntered

    private void prButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prButtonMouseExited

        prButton.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_prButtonMouseExited

    private void mrButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mrButtonMouseEntered

        mrButton.setForeground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mrButtonMouseEntered

    private void mrButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mrButtonMouseExited

        mrButton.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mrButtonMouseExited

    private void vrButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vrButtonMouseEntered

        vrButton.setForeground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_vrButtonMouseEntered

    private void vrButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vrButtonMouseExited
        
        vrButton.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_vrButtonMouseExited

    private void irButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irButtonMouseEntered
        
        irButton.setForeground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_irButtonMouseEntered

    private void irButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irButtonMouseExited
        
        irButton.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_irButtonMouseExited

    private void crButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crButtonMouseEntered
        
        crButton.setForeground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_crButtonMouseEntered

    private void crButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crButtonMouseExited
        
        crButton.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_crButtonMouseExited

    private void wrButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wrButtonMouseEntered
        
        wrButton.setForeground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_wrButtonMouseEntered

    private void wrButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wrButtonMouseExited
        
        wrButton.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_wrButtonMouseExited

    private void lrButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lrButtonMouseEntered
        
        lrButton.setForeground(Color.white);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_lrButtonMouseEntered

    private void lrButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lrButtonMouseExited
        
        lrButton.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_lrButtonMouseExited

    private void prButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prButtonActionPerformed

        if(projectCombo.getSelectedItem().equals("Select"))
        {
            project_nameLabel.setForeground(Color.red);
        }
        
        else
        {
            // DATABASE CODE HERE
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_prButtonActionPerformed

    private void projectComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectComboFocusGained

        project_nameLabel.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_projectComboFocusGained

    private void fromDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromDateFocusGained

        fromLabel.setForeground(Color.black);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_fromDateFocusGained

    private void projectComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectComboFocusLost

        if(projectCombo.getSelectedItem().equals("Select"))
        {
            project_nameLabel.setForeground(Color.red);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_projectComboFocusLost

    private void vrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrButtonActionPerformed

        if(projectCombo.getSelectedItem().equals("Select"))
        {
            project_nameLabel.setForeground(Color.red);
        }
        
        else
        {
            // DATABASE CODE HERE
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_vrButtonActionPerformed

    private void wrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrButtonActionPerformed

        if(projectCombo.getSelectedItem().equals("Select"))
        {
            project_nameLabel.setForeground(Color.red);
        }
        
        else
        {
            // DATABASE CODE HERE
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_wrButtonActionPerformed

    private void crButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crButtonActionPerformed

        if(projectCombo.getSelectedItem().equals("Select"))
        {
            project_nameLabel.setForeground(Color.red);
        }
        
        else
        {
            // DATABASE CODE HERE
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_crButtonActionPerformed

    private void mrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrButtonActionPerformed

        if(projectCombo.getSelectedItem().equals("Select"))
        {
            project_nameLabel.setForeground(Color.red);
        }
        
        else
        {
            // DATABASE CODE HERE
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_mrButtonActionPerformed

    private void irButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irButtonActionPerformed

        if(projectCombo.getSelectedItem().equals("Select"))
        {
            project_nameLabel.setForeground(Color.red);
        }
        
        else
        {
            // DATABASE CODE HERE
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_irButtonActionPerformed

    private void lrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lrButtonActionPerformed

        if(projectCombo.getSelectedItem().equals("Select"))
        {
            project_nameLabel.setForeground(Color.red);
        }
        
        else
        {
            // DATABASE CODE HERE
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_lrButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Reports().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton crButton;
    private org.jdesktop.swingx.JXDatePicker fromDate;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JButton irButton;
    private javax.swing.JButton lrButton;
    private javax.swing.JButton mrButton;
    private javax.swing.JButton prButton;
    private javax.swing.JComboBox projectCombo;
    private javax.swing.JLabel project_nameLabel;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JLabel report_typeLabel;
    private javax.swing.JLabel reportsLabel;
    private org.jdesktop.swingx.JXDatePicker toDate;
    private javax.swing.JLabel toLabel;
    private javax.swing.JButton vrButton;
    private javax.swing.JButton wrButton;
    // End of variables declaration//GEN-END:variables
}
