/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Wood.java
 *
 * Created on Feb 27, 2013, 3:53:07 PM
 */
package pos;

import java.awt.Color;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Home
 */
public class Wood extends javax.swing.JFrame {

    int temp = 0;
    JComboBox comboname;
    int exp=0,cost=0,quantity=0,total=0;
    
    
    /** Creates new form Wood */
    public Wood() {
        initComponents();
        setTitle("Add Wood");
        setSize(600,550);
        setVisible(true);
        setLocation(238,0);
        getContentPane().setBackground(new Color(129,134,138));
        Functions.FillCombo(vendorCombo, "VENNAME", "Vendor");
        Functions.FillCombo(wtypeCombo, "WOODTYPE", "Names");
        AutoCompleteDecorator.decorate(vendorCombo);
        AutoCompleteDecorator.decorate(wtypeCombo);
    }
    
    public Wood(int i,JComboBox combo)
    {
        initComponents();
        setTitle("Add Wood");
        setSize(600,550);
        setVisible(true);
        setLocation(238,0);
        getContentPane().setBackground(new Color(129,134,138));
        Functions.FillCombo(vendorCombo, "VENNAME", "Vendor");
        Functions.FillCombo(wtypeCombo, "WOODTYPE", "Names");
        AutoCompleteDecorator.decorate(vendorCombo);
        AutoCompleteDecorator.decorate(wtypeCombo);
        
        comboname = combo;
        temp = i;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_woodLable = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        woodLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        costTextField = new javax.swing.JTextField();
        vendorLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        billdate = new org.jdesktop.swingx.JXDatePicker();
        cancelButton = new javax.swing.JButton();
        wtypeCombo = new javax.swing.JComboBox();
        vendorCombo = new javax.swing.JComboBox();
        ExpLabel = new javax.swing.JLabel();
        ExpTextField = new javax.swing.JTextField();
        DetLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DetailsTextArea = new javax.swing.JTextArea();
        woodButton = new javax.swing.JButton();
        vendorButton = new javax.swing.JButton();
        cashLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        ExpLabel1 = new javax.swing.JLabel();
        BatchTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        add_woodLable.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        add_woodLable.setForeground(new java.awt.Color(0, 102, 102));
        add_woodLable.setText("Wood Stock");

        dateLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        dateLabel.setText("Bill Date");

        woodLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        woodLabel.setText("Wood Type");

        costLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        costLabel.setText("Cost");

        costTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                costTextFieldKeyReleased(evt);
            }
        });

        vendorLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        vendorLabel.setText("Vendor");

        quantityLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        quantityLabel.setText("Quantity");

        quantityTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityTextFieldKeyReleased(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        wtypeCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        wtypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        vendorCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        vendorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        ExpLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        ExpLabel.setText("Expenses");

        ExpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpTextFieldActionPerformed(evt);
            }
        });
        ExpTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExpTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ExpTextFieldFocusLost(evt);
            }
        });
        ExpTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ExpTextFieldKeyReleased(evt);
            }
        });

        DetLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        DetLabel.setText("Details");

        DetailsTextArea.setColumns(20);
        DetailsTextArea.setRows(5);
        jScrollPane1.setViewportView(DetailsTextArea);

        woodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        woodButton.setContentAreaFilled(false);
        woodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                woodButtonActionPerformed(evt);
            }
        });

        vendorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        vendorButton.setContentAreaFilled(false);
        vendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorButtonActionPerformed(evt);
            }
        });

        cashLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cashLabel.setForeground(new java.awt.Color(255, 0, 0));
        cashLabel.setText("Cash");

        totalLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        totalLabel.setText("Total");

        ExpLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        ExpLabel1.setText("Batch");

        BatchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatchTextFieldActionPerformed(evt);
            }
        });
        BatchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BatchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BatchTextFieldFocusLost(evt);
            }
        });
        BatchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BatchTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vendorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BatchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(woodLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(wtypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(dateLabel)
                                        .addGap(41, 41, 41)
                                        .addComponent(billdate, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ExpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(quantityLabel)
                            .addComponent(ExpLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costLabel)
                                    .addComponent(vendorLabel)
                                    .addComponent(totalLabel))
                                .addGap(51, 51, 51)
                                .addComponent(cashLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ExpLabel)
                            .addComponent(DetLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(woodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(add_woodLable)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_woodLable)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(billdate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(woodLabel)
                    .addComponent(wtypeCombo)
                    .addComponent(woodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BatchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLabel)
                    .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorLabel)
                    .addComponent(vendorCombo)
                    .addComponent(vendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DetLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(cashLabel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    
    
    String woodtype,vendor,details;
    
    
    int flag = 0;
    
    
    if(wtypeCombo.getSelectedItem().equals("Select"))
    {
        woodLabel.setForeground(Color.red);
        flag++;
    }
    else
    { woodLabel.setForeground(Color.black);
    }
    if(costTextField.getText().equals(""))
    {
        costLabel.setForeground(Color.red);
        flag++;
    }
    else
    {
         costLabel.setForeground(Color.black);
    }
    if(billdate.getEditor().getText().equals(""))
    {
        dateLabel.setForeground(Color.red);
        flag++;
    }
    else
    {
    dateLabel.setForeground(Color.black);
    }
    if(vendorCombo.getSelectedItem().equals("Select"))
    {
        vendorLabel.setForeground(Color.red);
        flag++;
    }
    else
    {
      vendorLabel.setForeground(Color.black);   
    }
    if(quantityTextField.getText().equals(""))
    {
        quantityLabel.setForeground(Color.red);
        flag++;
    }
    else
    {
        quantityLabel.setForeground(Color.black);
    }
    if(!ExpTextField.getText().equals(""))
    {
        exp = Integer.parseInt(ExpTextField.getText());
            }
    
        
        
    if(flag==0)
    {
       
    details = DetailsTextArea.getText();
    woodtype = (String) wtypeCombo.getSelectedItem();
    cost = Integer.parseInt(costTextField.getText());
    vendor = (String) vendorCombo.getSelectedItem();
    quantity = Integer.parseInt( quantityTextField.getText());
        total = cost*quantity+exp;
        int bno = 0 ;
        try {
                  Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                  Connection con = DriverManager.getConnection("jdbc:odbc:indlands","","");
                  Statement  st = con.createStatement();
                  ResultSet res = st.executeQuery("select INVNO from Wood ");
                  Boolean rec = res.next();
                  System.out.println("connected successfully");
                  do
                  {
                     if(rec==true) {
                      bno =res.getInt(1);
                      }
                  }while (res.next());
                  
                bno+=1 ;
        
        }
        catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"The error is1:"+e);
                System.out.println(e.getMessage());
            } 
        
       try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           Connection con=DriverManager.getConnection("jdbc:odbc:indlands","","");
           SimpleDateFormat formater = new SimpleDateFormat("MM/dd/yyyy");
           String newdate=    formater.format(billdate.getDate()); 
                     
           PreparedStatement prp=con.prepareStatement("INSERT INTO Wood (WOODTYPE,VENDOR,QUANTITY,COST,EXT_EXP,EXT_EXP_DET,TOTAL,BILLDATE) VALUES(?,?,?,?,?,?,?,?)");
           prp.setString(1,woodtype);
           prp.setString(2,vendor);
           prp.setInt(3,quantity);
           prp.setInt(4,cost);
           prp.setInt(5,exp);
           prp.setString(6,details);
           prp.setInt(7,total);
           prp.setString(8,newdate);
           prp.executeUpdate();
           //JOptionPane.showMessageDialog(null,"Wood Details added Succesfully");
           
           if(temp == 1)
           {
              comboname.addItem(bno);
              comboname.setSelectedItem(bno);
           }
           
           wtypeCombo.setSelectedItem("Select");
           costTextField.setText("");
           vendorCombo.setSelectedItem("Select");
           quantityTextField.setText("");
           ExpTextField.setText("");
           DetailsTextArea.setText("");
           con.commit();
           con.close();
           Functions.DisposeFunc(this);
       }
       catch(SQLException e)
       {
           JOptionPane.showMessageDialog(null,"INVALID DATATYPE");
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,"The error is : "+e);
           System.out.println(e.getMessage());
       } 
    }
}//GEN-LAST:event_saveButtonActionPerformed

    private void costTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costTextFieldKeyReleased

        if(Functions.NumericValidate(costTextField))
        {
            if(costTextField.getText().equals(""))
            { cost = 0;}
            else
            {
                cost =Integer.parseInt( costTextField.getText());
            }
             if(ExpTextField.getText().equals(""))
            {
                exp = 0;
            }
            else
            {
                exp = Integer.parseInt(ExpTextField.getText());
            }
             if (quantityTextField.getText().equals(""))
             {
                 quantity=0;
             }
             else
                 
             {
                quantity=Integer.parseInt(quantityTextField.getText()) ;
             }
        }
        total = cost*quantity+exp;
        
          cashLabel.setText(Integer.toString(total));
       
    }//GEN-LAST:event_costTextFieldKeyReleased

    private void quantityTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTextFieldKeyReleased

        Functions.NumericValidation(quantityTextField);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextFieldKeyReleased

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void ExpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpTextFieldActionPerformed

    private void ExpTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExpTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpTextFieldFocusGained

    private void ExpTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExpTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpTextFieldFocusLost

    private void ExpTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExpTextFieldKeyReleased
         if(Functions.NumericValidate(ExpTextField))
        {
            if(costTextField.getText().equals(""))
            { cost = 0;}
            else
            {
                cost =Integer.parseInt( costTextField.getText());
            }
             if(ExpTextField.getText().equals(""))
            {
                exp = 0;
            }
            else
            {
                exp = Integer.parseInt(ExpTextField.getText());
            }
             if (quantityTextField.getText().equals(""))
             {
                 quantity=0;
             }
             else
                 
             {
                quantity=Integer.parseInt(quantityTextField.getText()) ;
             }
        }
        total = cost*quantity+exp;
        
        cashLabel.setText(Integer.toString(total));
    }//GEN-LAST:event_ExpTextFieldKeyReleased

    private void vendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorButtonActionPerformed
      Vendor vendor=new Vendor(1,vendorCombo);            // TODO add your handling code here:
    }//GEN-LAST:event_vendorButtonActionPerformed

    private void woodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_woodButtonActionPerformed
  String woodnew =  JOptionPane.showInputDialog(null, "Enter New Wood Type");
        while (woodnew.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter New Wood Type");
            woodnew = JOptionPane.showInputDialog(null, "Enter New Wood Type");
        }
        try{
            
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                Connection con = DriverManager.getConnection("jdbc:odbc:indlands","","");
                 PreparedStatement prp=con.prepareStatement("insert into Names(WOODTYPE) values(?)");
                 prp.setString(1, woodnew);
                 prp.executeUpdate(); 
                 wtypeCombo.setSelectedItem(woodnew);
                  con.commit();
                  con.close();
        }
         
             catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,"Err is"+e);
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"The error is1:"+e);
             }            // TODO add your handling code here:
    }//GEN-LAST:event_woodButtonActionPerformed

    private void BatchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BatchTextFieldActionPerformed

    private void BatchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BatchTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BatchTextFieldFocusGained

    private void BatchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BatchTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_BatchTextFieldFocusLost

    private void BatchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BatchTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BatchTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Wood().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BatchTextField;
    private javax.swing.JLabel DetLabel;
    private javax.swing.JTextArea DetailsTextArea;
    private javax.swing.JLabel ExpLabel;
    private javax.swing.JLabel ExpLabel1;
    private javax.swing.JTextField ExpTextField;
    private javax.swing.JLabel add_woodLable;
    private org.jdesktop.swingx.JXDatePicker billdate;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cashLabel;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField costTextField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton vendorButton;
    private javax.swing.JComboBox vendorCombo;
    private javax.swing.JLabel vendorLabel;
    private javax.swing.JButton woodButton;
    private javax.swing.JLabel woodLabel;
    private javax.swing.JComboBox wtypeCombo;
    // End of variables declaration//GEN-END:variables
}
